### ISSUE TITLE
Send Later not placing message in drafts

### ISSUE THREAD

**Issue by epsso** [Extended-Thunder/send-later#102]
After successfully sending 3-4 messages via Send Later, the extension stops placing messages in the draft folder when sent though a gmail.com account.  When outgoing mail is through a non gmail.com account Send Later works as expected.  I have attached a zipped video file of what is occurring, a copy of the console log, and a screen shot of the Send Later settings.  The issue exists when Send Later is the only extension that is enabled.  If I restart TB I am able to successfully send about 3-4 messages via Send Later then it stops working again.

TB: 78.4.3
Send-Later: 8.1.0
OS: Windows 10 Pro Version 10.0.19041

[Send Later.zip](https://github.com/Extended-Thunder/send-later/files/5533485/Send.Later.zip)
[console-export-2020-11-12_14-29-6.txt](https://github.com/Extended-Thunder/send-later/files/5533486/console-export-2020-11-12_14-29-6.txt)
![Send Later Settings](https://user-images.githubusercontent.com/26418430/99000665-42265180-24ff-11eb-8737-a8e898d000cc.jpg)

**Comment by jperryhouts** [comment]
I think this is related to an [open Mozilla bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1640407), which appears to be a similar sort of problem (although not directly related) to what's going on in #16. I think in this case there is an internal problem with closing the popup dialog, which is not caught early enough and so it blocks the save operation from completing. I'll look into whether there's a way for Send Later to work around this, but ultimately this will have to be fixed in Thunderbird.

**Comment by jperryhouts** [comment]
Looking into it more, and comparing your log file to the screencast (very helpful, thank you for doing that by the way), I'm less convinced about my original diagnosis. It might have to do with gmail's imap server or some other thing blocking saving to drafts.

For what it's worth, draft folders (and trash) in gmail accounts are handled awkwardly by Thunderbird. In my case, there is a separate Drafts folder outside of the "Gmail" subfolder

![Screenshot from 2020-11-21 13-43-11](https://user-images.githubusercontent.com/6118266/99888346-fa8b7e00-2c00-11eb-9f4b-a2fb31f6645c.png)

When you ctrl+s from a composition window, does it put the draft where you expect? If not it's worth checking your "Copies and Folders" settings for that account, in case Drafts are saved somewhere unexpected.

#134 addresses this by checking that save to drafts was successful before closing the composition window. This is more of a workaround than a solution, but it seems like it's the best that can be done on my end.

That change won't make it into the release version until next weekend (v8.3.x), since I'm on a de-facto 1-week release schedule. I'm closing this issue for now, but let me know if the problem persists after that and we can reopen it.

**Comment by epsso** [comment]
In Account Settings -> ***@gmail.com -> Copies & Folders the Drafts and Templates options was set to Other: Drafts on ***@gmail.com. It was placing the drafts in ***@gmail.com -> [Gmail] -> drafts folder.  When I changed the setting to "Drafts" folder on ***@gmail.com it placed the drafts in ***@gmail.com -> Drafts.  I will try #134 and let you know if this resolves the issue.

**Comment by jperryhouts** [comment]
I'll generate a release package for the current development branch in a couple of hours. Keep an eye on https://github.com/Extended-Thunder/send-later/releases for that

**Comment by epsso** [comment]
I have updated to TB 78.5.0 and Send Later 8.3.0 and am still having the issue with outgoing gmail when I use either of the drafts folder in the gmail account.  When I change the Drafts folder to Other: Drafts on Local Folders it works great.  Also it is faster as it does not have to go out and save into a network drafts folder.

**Comment by jperryhouts** [comment]
Interesting. That sounds related to #16 and might provide some clues about it if so.
