### ISSUE TITLE
Send Later Column in Upon Startup

### ISSUE THREAD

**Issue by SilverknightFL** [Extended-Thunder/send-later#120]
Upon startup, in whatever was the last mailbox/folder I was in, it starts with a Send Later column in the far left.

This goes away, once any email is opened or moving to another mailbox or folder. It is in
![Capture](https://user-images.githubusercontent.com/74670060/99552023-8a73c280-298a-11eb-9e58-fc199aca27b0.PNG)
 the drop down menu for the headers.

**Comment by jperryhouts** [comment]
This behavior is improved in the next release, but there are some quirks in the way columns are added that need to be fixed in thunderbird before this can have a very reliable solution.

Can you confirm that this only happens for you immediately after installing Send Later, or does it happen every time you start Thunderbird?

**Comment by jikamens** [comment]
Also, another user reports (on the send-later-users mailing list):

>in my thunderbird (v.78.5) with send later extension (v. 8.1)
>i am not able to disable the Send Later Column.
>i mean that even if it is disabled in the preferences of the extension,
>it appears in the thread pane.

Not sure if this is going to be addressed by the changes in the next release.

**Comment by SilverknightFL** [comment]
Odd, because if I bring up the row check boxes, it's the first one but goes away when unchecked. Until next TB launch. So something is checking it or it should not be in the check list. Please forgive any typos as this email was composed on a device without a real keyboard.Michael Silbergleid561-379-7387On Nov 19, 2020 1:50 PM, Jonathan Kamens <notifications@github.com> wrote:
Also, another user reports (on the send-later-users mailing list):

in my thunderbird (v.78.5) with send later extension (v. 8.1)
i am not able to disable the Send Later Column.
i mean that even if it is disabled in the preferences of the extension,
it appears in the thread pane.

Not sure if this is going to be addressed by the changes in the next release.

**Comment by jperryhouts** [comment]
> Also, another user reports (on the send-later-users mailing list):
> 
> > in my thunderbird (v.78.5) with send later extension (v. 8.1)
> > i am not able to disable the Send Later Column.
> > i mean that even if it is disabled in the preferences of the extension,
> > it appears in the thread pane.
> 
> Not sure if this is going to be addressed by the changes in the next release.

This is weird, because the "show column..." option is a necessary conditional for setting the column visible, regardless of any other options. And if the overlay were not receiving options correctly, it should still default to hidden. This might be fixed in the next release, just because there are a handful of improvements there related to overlays, but I wouldn't have expected this to happen at all to begin with.

> Odd, because if I bring up the row check boxes, it's the first one but goes away when unchecked. Until next TB launch. So something is checking it or it should not be in the check list.

This sounds much more like the problem that other extensions were having, where the state of the column didn't persist across restarts. The fixes in the next release will improve this (ensuring it doesn't show up in the wrong folders), but if you want to remove it entirely just uncheck the "show column ..." option in send later's settings (at least that's how it should work, previous comment notwithstanding).

**Comment by jperryhouts** [comment]
This should be fixed by #133 and #136
