### ISSUE TITLE
send later does not work when account server settings are set to" just mark as deleted"

### ISSUE THREAD

**Issue by hrudy** [Extended-Thunder/send-later#126]
Duplicated on a Mac using TB 78.4.3 and Send-later 8.1. 0
Send Later complains about corrupted drafts folder if there are any deleted items in it.

This used to work in previous versions

**Comment by jperryhouts** [comment]
Thanks for the heads up. I think this should be an easy fix, but I'll look into it more over the weekend.

**Comment by jperryhouts** [comment]
This turns out to be less trivial than I expected. Thunderbird doesn't have a way to identify which messages are flagged as deleted, so as far as extensions know they're all valid messages. Send Later complains because encountering a message in Drafts that should have been deleted usually indicates something is wrong with your message index database, thus the warning.

This is not an ideal solution, but #144 provides a workaround by offering the option to silence those warnings, and silently skip messages which it has previously sent. This is going to have to do for now, until Thunderbird adds a mechanism for differentiating messages which have been flagged as deleted and ones which are not. I opened a [bugzilla report](https://bugzilla.mozilla.org/show_bug.cgi?id=1678964) about it, but there's no telling when that will get resolved.
