### ISSUE TITLE
Accelerators for buttons in Send Later pop-up

### ISSUE THREAD

**Issue by jikamens** [Extended-Thunder/send-later#149]
Feedback from a user sent via email:

>One thing I am missing in the new version though are the accelerator keys on the buttons in the SendLater dialog. I especially often used Alt-J for "Send now" in German. Obviously the way the buttons are being created/locale strings used doesn't let me just add an "&" in front of the respective letter in the locale string (which I tried and got a literal "&" in the label)...would there possibly still be a way to add those accelerators?

This is a loss of functionality from the TB68 version of Send Later.

**Comment by jperryhouts** [comment]
It took me a minute to understand what they were trying to do with &, but that's clever. I didn't know that was possible in the TB68 version. There was similar discussion in #100, which unfortunately didn't come to anything. In that case it came down to inflexibility in the mailextension api.

Similarly, mailextensions won't be able to bind arbitrary key combinations, but they can bind some fixed combinations via manifest entries that always correspond to the shortcuts (like alt+1 / alt+2 / alt+3 as in the 7.x branch).

**Comment by kleena-k** [comment]
Hi jperryhouts,

I have reported the issue to Jonathan Kamens. The "&" thing was a desperate (and futile) attempt of a Windows user to assign an accelerator key to a localized string. I can't tell if that worked like that in the TB68 version, but the accelerator keys were there and the German version had the "J" in "Jetzt senden" react to the corresponding Alt-shortcut.

It'd be cool if you found a way to do that - I am using "SendLater" to intercept all send mails and ask me when to send it, forcing me to leave the keyboard and move the mouse to choose one of the buttons, which doesn't exactly improve my productivity ;)

Thank you, best regards
Viktor

**Comment by jperryhouts** [comment]
#163 implements all of the original shortcuts that I was aware of.

In the composition window those are Ctrl+Alt+1, Ctrl+Alt+2, and Ctrl+Alt+3 for shortcuts 1 2 and 3 respectively, and within the popup dialog those are Ctrl+Enter triggers the 'send at ...' button, and Ctrl+1, Ctrl+2 and Ctrl+3 trigger the shortcuts.

From within the popup dialog itself it's possible to bind whatever shortcuts we want, because send later gets full control over that window, but I'm not sure how the ctrl+j default behavior worked in the previous version.

@jikamens could you fill me in on how that behaved? Did it indeed bind to ampersand-prefixed characters in the shortcut labels?

**Comment by jperryhouts** [comment]
Nevermind, I figured it out. I'll get a patch together to re-implement those access keys as well.

**Comment by jperryhouts** [comment]
This is fixed by #167. The correct locale-aware default keys now bind to "Send Now" and "Place in Outbox", plus the ctrl+1|2|3 combinations which bind to the shortcuts. **And** based on the idea from @kleena-k, if you place an `&` in a shortcut label it will also bind the following character as an access key to that shortcut.
