### ISSUE TITLE
Send Later 8.2.1 stopped working?

### ISSUE THREAD

**Issue by itamarh** [Extended-Thunder/send-later#162]
add-on enabled. not showing send later button, ctrl-shift-enter does not trigger dialog, send-later header not in columns, etc.
Thunderbird version: thunderbird-78.4.0-1.fc33.x86_64

worked yesterday... didn't work today. upgrading add-on to 8.2.1 didn't solve. disabling/enabing the plugin and/or restarting thunderbird didn't solve.

no other plugin installed

any logs/info I can provide?

**Comment by jperryhouts** [comment]
Can you explain what does happen when you do these things? It's hard to debug just based on what doesn't happen.

I don't know what would be causing this, but there have been lots of changes to Send Later since version 8.2.1. It will be more helpful to debug against the most recent version (8.4.5), but that is currently waiting on review before it gets posted to addons.thunderbird.net, and there appears to be a big queue of addons waiting for review right now. Alternatively, you can get the release from the [release page](https://github.com/Extended-Thunder/send-later/releases/tag/8.4.5), and install it from the addons page with "install addon from file".

Either way, give version 8.4.5 a shot and let me know if this is still happening. We can take it from there.

**Comment by itamarh** [comment]
it was just like if it wasn't installed at all.
before going to different versions, I just removed and installed it again which solved it.
I'll close this for now and let's see if this behaviour recurs again first (suddenly not working despite installed)

**Comment by jperryhouts** [comment]
Something similar happened to me once, where Thunderbird straight up uninstalled send later immediately after updating it without any notification. I still have no clue how or why that happened, but I was never able to reproduce it. :shrug:

Let me know if this does happen again.
