### ISSUE TITLE
Missing Danish translation strings

### ISSUE THREAD

**Issue by FinnVonB** [Extended-Thunder/send-later#191]
Hi Jonathan.

Sorry issue #121 is NOT solved by issue #131 though You have closed it.

Only change is that the headlines in 'settings'  are in English and not German / Dutch.
Rest is same issue ;-)
Regards,

**Comment by jperryhouts** [comment]
Thanks for the heads up.

My project for next weekend is getting the whole translation setup via Crowdin setup for the new version, so this will hopefully be fixed soon.

**Comment by jph-sendlater** [comment]
Unless I missed something, there were already a ton of missing Danish strings in Send Later 7.4.4. The fix that @jikamens [implemented in May](https://github.com/jikamens/send-later/commit/09796119182269f10e3bb8d8f6ec053aac3ec42d) removed some errant Dutch strings from the Danish locale, but I assume you still got a lot of mixed languages in your UI because the Danish locale was only like 10% complete. Are there other translation strings that I'm not aware of?

In any case, I finally got Crowdin support back up and running, under a new project name: https://crowdin.com/project/sendlater/ (I'll get the docs updated to reflect that soon). I imported a bunch of auto-translated strings for Danish just now in #249 . It's still incomplete, and I'm guessing a lot of the auto-translator strings are incorrect. If you're interested in contributing it would be very much appreciated. You just need to [make an account on Crowdin and start editing the Send Later project](https://crwd.in/sendlater).

**Comment by jikamens** [comment]
@jph-sendlater if you let me know what your email address is on Crowdin then I can make you an admin of the existing Send Later project and you can upload stuff there rather than using a new project. I have a team of translators there, many of whom will presumably be willing to continue to help, and I don't think you want to have to build back up the team from scratch!

**Comment by jph-sendlater** [comment]
:+1: Thanks! I made the crowdin account under jph@extended-thunder.org.

**Comment by jikamens** [comment]
Invite sent.

**Comment by jph-sendlater** [comment]
Great. I'm attempting to connect it with the github repository. Worked great starting from an empty crowdin project, but we'll see how it does syncing with one that has some history to it. Fingers crossed I don't somehow ruin everything in the process :worried:

**Comment by jph-sendlater** [comment]
Never mind. That seemed to be surprisingly painless, and the GitHub integration seems to work great. Crowdin automatically creates pull requests when things change.
