### ISSUE TITLE
Mails stay in the drafts folder and are not sent later when OpenPGP is enabled

### ISSUE THREAD

**Issue by yahesh** [Extended-Thunder/send-later#193]
When using Thunderbird 78 and the introduced OpenPGP support, all drafts are encrypted with the sender's key. Without warning, send-later will not send mails but they will stay in the draft folder. When clicking the "Send Later" button of such a draft, you're greated with the message _"ERROR Message is encrypted and will not be prcoessed by Send Later."_ This is problematic when new users expect the addon to work and have to manually find out that their use-case is not supported.

**Expected behaviour:**

Mails get sent later **or** an active warning is provided that mails will not be sent due to incompatibility.

**Actual behaviour:**

Mails do not get sent and there is no active warning. The user has to manually find out why the mails do not get sent.

**Additional information:**

**OS:** macOS Catalina 10.15.17
**Thunderbird:** 78.5.0
**OpenPGP:** enabled
**Send-Later:** 8.4.5

**Comment by jperryhouts** [comment]
Send later is unfortunately fundamentally incompatible with PGP, at least as it is currently implemented in Thunderbird 78, since there's no way to disable encrypting draft messages. This has been discussed in previous issues.

This weekend I'll look into ways to detect that PGP is enabled ahead of time in order to warn the user. At the very least, I should make sure that the drafts column does not display a schedule for encrypted messages, since that would definitely be misleading.

**Comment by yahesh** [comment]
Nah, too bad. I hoped that Send-Later could solve a problem, but being able to use OpenPGP is a hard requirement for me.
