### ISSUE TITLE
Messages to be sent in the future should show the scheduled time, not the time of draft being saved

### ISSUE THREAD

**Issue by wuhandong** [Extended-Thunder/send-later#25]
In old versions the draft saved would show the scheduled send-out time, not the current time (the time the draft being saved).  In TB 78.3.1 with Send-Later 8.0.5, scheduled messages show the time of draft being saved, instead of scheduled send-later time.  

Many thanks for working on the project.

**Comment by jperryhouts** [comment]
The old version had a separate column in the drafts folder to identify when it is scheduled to send. That is by far the number 1 feature request for the new version, and I'm hoping to finish it up this weekend.

FYI you can see the message's scheduled time by viewing it in the Drafts folder, and a "Send Later" action button should appear in the message header toolbar. Clicking that button will show you the schedule.

I'm going to close this issue, because it is already mentioned in #7 and #17
