### ISSUE TITLE
encrypted drafts sends emails encrypted with my pub key

### ISSUE THREAD

**Issue by Geremia** [Extended-Thunder/send-later#26]
With encrypted drafts (using Thunderbird 78's built-in OpenPGP), SendLater sends the emails encrypted with *my* public key.

**Comment by jperryhouts** [comment]
This could be challenging to address, because Send Later relies on draft messages for storage. If your PGP key has a passphrase there is no automated way to open / read those messages without user intervention.

I believe this was the case with the legacy Send Later as well, at least with the p≡p system in Thunderbird 68. It actually caught me off guard sending an important email about a job offer, which was pretty awkward. I just disabled OpenPGP after that, because I so rarely needed it, and I didn't want to be surprised by something like that again.

I think the best solution for the time being will be to check whether encrypted drafts are enabled, and present the user with an error message, preventing them from attempting to schedule a message in the first place. In the long term I would be interested in exploring options for some other method of storing scheduled messages. Using the Drafts folder has always felt like a bit of a hack, and may become impossible depending on future webextension API changes anyway.

**Comment by Geremia** [comment]
@jperryhouts 

>will be to check whether encrypted drafts are enabled

Do you know a way of disabling it in TB 78 (besides disabling OpenPGP)?

**Comment by jperryhouts** [comment]
> Do you know a way of disabling encrypted drafts in TB 78 (besides disabling OpenPGP)?

@Geremia I'm not aware of one. It used to be a separate option if I recall, but it looks like they've dumbed down their options a lot and that might have gotten lost in the shuffle. Maybe it's still hidden somewhere that I'm not aware of, though.

Fortunately, it's easy to test if a scheduled message is encrypted. It looks like they always have a header like `Content-Type: application/pgp-encrypted`. That will at least make it easy to avoid sending these messages by mistake. I've run out of time to work on this for right now, but this is on my list for next weekend.

**Comment by msebald** [comment]
Having the same problem and opened up a dupe issue #38, sorry.

Sad to here that there is no way to disable encrypted drafts. For me, I do not need it. It is enough for me sending some messages encrypted, and some more signed. I know that saving unencrypted drafts might be a security issue, but not in my case. It should be an option to turn it off.

Any idea who we could ask about that? Just opening up a feature request at Thunderbird bug reporting site?

**Comment by msebald** [comment]
Just opened up a feature request at Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1672047

**Comment by jperryhouts** [comment]
#57 implements a failsafe to prevent accidentally sending self-encrypted emails. This is not really a satisfactory solution, as all it does is effectively prevent send later from functioning when openPGP is enabled. But Send Later is very limited in this respect, and doing anything to override Thunderbird's encryption functionality is obviously the wrong approach here.

Hopefully the feature request that @msebald opened on Bugzilla gains traction.
