### ISSUE TITLE
Send Later updates reset Write window

### ISSUE THREAD

**Issue by tplanter** [Extended-Thunder/send-later#281]
Every time there is a Send Later update, the Write window is reset to the default, meaning there is no Send Later button (or even Send button) on the toolbar. A restart of TB does not fix the problem.
I modify the toolbar to have the Send Later button on the left hand side of the Write window - as it used to be in the old version. After an update and restart, the Send Later button re-appears, but on the right hand side.
I'd prefer it to stay where I placed it.

**Comment by jph-sendlater** [comment]
This is one of those things that needs to be fixed in Thunderbird. -- Same with the drafts column, which has a tendency to snap back to its default spot during restarts and updates. These are problems that Send Later *could* try to work around with some convoluted finagling, but any real solution has to come from the Thunderbird side. Lots of work is going on from their end to stabilize the new extension API, but it's a slow process.

So, sorry to say but I'm chocking these sorts of issues up to growing pains in Thunderbird that are just going to have to wait.
