### ISSUE TITLE
Send Later breaks Copy Sent To Current addon

### ISSUE THREAD

**Issue by hameau** [Extended-Thunder/send-later#283]
Hello,

Thunderbird 78.6.1 (64-bit)
Send Later 8.7.2
Copy Sent To Current 3.7 https://addons.thunderbird.net/en-US/thunderbird/addon/copy-sent-to-current/
Debian 10 (buster)

Copy Sent To Current allows sent mail to be automatically placed in any mail folder. If replying to an existing message, it optionally allows the original message to be moved to the same folder. The target folder is specified in an FCC: header at the time of sending (or placing in Outbox for messages to be sent later, using the Thunderbird 'Send Unsent Messages' feature).

Using Send Later addon, when a message is scheduled for later sending, the FCC: header is set to the Thunderbird preference (Account Settings -> Copies & Folders), ignoring the Copy Sent To Current setting. This can be seen in the source view of scheduled messages in the Drafts folder.

If a message is sent using the Send Later 'Send Now' or 'Put in Outbox' buttons, the FCC: header from Copy Sent To Current is preserved and it's disposition is to the correct folder.

This used to work, but I'm afraid I don't know exactly when it stopped – almost certainly with the upgrade to Thunderbird 78 (I upgraded from 68 to 78 in early December 2020), but everything was in turmoil then, of course.

I have sent a message to the developer of Copy Sent To Current (G.Gersdorf@ggbs.de), with a link to this issue report.

**Comment by jph-sendlater** [comment]
I assume this is related to #262, since Send Later currently bypasses the proper message send sequence. Basically, other add ons will not be notified and will not process the message as they usually would. This is a high priority for me, but things are pretty busy for me at the moment so I unfortunately won't get to it for at least a few weeks. Sorry for the inconvenience in the mean time!

I'm going to close this issue just to keep things tidy, but I suggest keeping an eye on #262 for updates related to this.

**Comment by hameau** [comment]
Thanks. I saw #262 and wondered if it might be connected but didn't want to guess ...
