### ISSUE TITLE
Incompatible with Thunderbird 87.0

### ISSUE THREAD

**Issue by elnecio69** [Extended-Thunder/send-later#299]
Looks like latest update has derailed this wonderful tool.

**Comment by jph-sendlater** [comment]
I generally do not support the Thunderbird beta channel because it's such a fast moving target, especially recently. However, you can get the beta release of send later here: https://github.com/Extended-Thunder/send-later/releases
I just updated it to allow installation on Thunderbird 87. Let me know if you run into any problems with that.
