### ISSUE TITLE
[Enhancement] Allow override of default selected delay behavior with "Send Now" action 

### ISSUE THREAD

**Issue by oleole39** [Extended-Thunder/send-later#337]
Hello,

I enabled the option which makes all the emails to be sent with a delay of 5mn by default, which I am happy with (thank you by the way for this plugin!).

However, sometimes I need to send an email right away. 
To do so the only way I found so far (despite reading the documentation - or did I miss something?) is to disable the plugin/or uncheck the option in the plugin's settings page, send my email, and re-enable the plugin/or the option.

It would be great to have more convenient way to override the default selected behavior, I can think of:
- a down-arrow on the right of the "Send button" which would open a drop-down menu showing the option "Send now" below the option "Send";
- OR/AND a dedicated keyboard shortcut to "send now".

**Comment by jph-sendlater** [comment]
That's possible. You can do it with the "Send Now" button at the bottom of the scheduler dialog. You can also open the dialog and activate 'send now' with hotkeys: https://extended-thunder.github.io/send-later/#hot-keys

Unfortunately the dynamic functions can't directly activate send now, but you can set one of the shortcuts to "Delay: 0" so that the message sends next time Send Later does its check. I personally set the "Check every __ minutes" to 0.25, so "delay 0" means "send message within 15 seconds"

That enables much more flexibility, because you can attach the shortcuts to actions like Ctrl+1 , or when you shift+click on the Send Later button, for example.

![image](https://user-images.githubusercontent.com/75693008/121738880-af0ec380-caaf-11eb-9ff3-d924d154cca2.png)

![image](https://user-images.githubusercontent.com/75693008/121738745-77078080-caaf-11eb-8ad1-18ccc8ecdcdf.png)

**Comment by oleole39** [comment]
Thank you for your reply.

I had actually tried the Send Now button at the bottom of the scheduler dialog but:
- mail was not being sent 
- legacy send button was becoming greyed at the same time (I had to save to draft, close the email and open it again so that it becomes clickable again). 
At that point, I assumed that the Send Now from the scheduler dialog button was somehow not supposed to work when "Send with delay of X mn by default" option was enabled. 
However after reading your reply and making a few tests, I understand that this is due to a conflict with ["Check and Send" plugin](https://addons.thunderbird.net/en-US/thunderbird/addon/check-and-send/) I use for other purposes (mostly to check against some words and not to forget to add mentioned attachments).

But even with Check and Send plugin enabled, I manage to send with 10sec delay with the Ctrl+click shortcut  (which I had not tried back then). So it is enough for me. Thanks again.
