### ISSUE TITLE
Emails Stuck in Outbox

### ISSUE THREAD

**Issue by Shimergo** [Extended-Thunder/send-later#371]
I have a pile of 'send later' emails, a mix of recurring and one-offs. I've just added a new email account to Thunderbird, and set it to use the Global Inbox. And I've now started editing each of the 'send later' emails in the Drafts folder to change the to/from address from the old (not working) email to the new one. But when the time comes for one of these to send, it moves it into the Outbox, updates it to a new date in Drafts (if recurring), but doesn't actually send. It's the same if I setup a one-off test 'send later' mail - it just goes to the Outbox then nowhere. But doing a normal (immediate) send works fine (using the same to/from addresses as the failing 'send later' emails, ie. both as the new email address).
If it helps, there's also a bar at the bottom of the TB window that's constantly scanning with "Send Later [PEND 55]" next to it.
Am I doing something wrong? How can I get 'send later' working again.

**Comment by jph-sendlater** [comment]
This is almost always a problem in Thunderbird, since by the time the message is in the outbox, it is mostly ouside of the send later extension's control. There is a section in the docs that covers troubleshooting steps you can take to isolate the problem : https://extended-thunder.github.io/send-later/#troubleshooting

The most common cause I've heard reports of recently is related to a Thunderbird profile problem, where the "default account" gets an invalid value for one reason or another. The troubleshooting guide will direct you to instructions on fixing that if it is the case.

**Comment by Shimergo** [comment]
Thanks - Yep, seems to be working now I've removed the rogue account.
