### ISSUE TITLE
Short cut for Day of the Week and Time

### ISSUE THREAD

**Issue by dzlater** [Extended-Thunder/send-later#382]
First off, thanks for the terrific add on, I can't tell you how helpful this is. 

Would it be possible to add an enhancement ?
I have a batch of emails that I prepare during the week and send on Friday at 11 am.
It would be very helpful to have a short cut for this. Currently, I have to set the date and time and use it as the default setting. or just enter the date and time manually for each message.

Thank you for considering this request.

**Comment by jph-sendlater** [comment]
This is already possible. You have a few options:

1. You can assign one of the shortcuts to the "BusinessHours" function, with arguments: `[5], [11,0], [11,0]`
![image](https://user-images.githubusercontent.com/75693008/134413531-7c15f447-7fad-45b9-aa06-39a5c367fcfc.png)
2. As you mentioned, you can set a default. You don't need to set it to a specific date/time; you can use something like "`Friday at 11:00`", and then hit "Save these values as defaults". If this really is the most common schedule you use, I would suggest this method, since it's simplest.
3. If you need something more complicated, you can always make a custom function, and assign it to one of the shortcuts. This is more involved, but also much more flexible. There are details on how to do it in the [documentation](https://extended-thunder.github.io/send-later/#dynamic-function-editor)

**Comment by dzlater** [comment]
Thanks for the ideas.
I'll give them a try. 

On September 22, 2021 4:06:19 PM EDT, jph-sendlater ***@***.***> wrote:
>This is already possible. You have a few options:
>
>1. You can assign one of the shortcuts to the "BusinessHours" function,
>with arguments: `[5], [11,0], [11,0]`
>![image](https://user-images.githubusercontent.com/75693008/134413531-7c15f447-7fad-45b9-aa06-39a5c367fcfc.png)
>2. As you mentioned, you can set a default. You don't need to set it to
>a specific date/time; you can use something like "`Friday at 11:00`",
>and then hit "Save these values as defaults". If this really is the
>most common schedule you use, I would suggest this method, since it's
>simplest.
>3. If you need something more complicated, you can always make a custom
>function, and assign it to one of the shortcuts. This is more involved,
>but also much more flexible. There are details on how to do it in the
>[documentation](https://extended-thunder.github.io/send-later/#dynamic-function-editor)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Extended-Thunder/send-later/issues/382#issuecomment-925289643

-- 
David M. Slater
Executive Director
Old Colony Library Network Inc.
781-794-2413 x812
***@***.***
