### ISSUE TITLE
Send Later does not send even after Upgrade to 91.1 and OPGP fix

### ISSUE THREAD

**Issue by farfallosa** [Extended-Thunder/send-later#383]
in Version 91.1 thunderbird allows to save drafts without encryption. But send later nevertheless does not send as intended.
If I try to send an email e.g. fifteen minutes postponed using send later, the email remains in draft folder and is not delivered.
(Subject is set not to encrypt, the email is signed but not encrypted.)

Is there a fix to get send later now working with actual version of thunderbird and OPGP?
Thanks,  will

**Comment by jph-sendlater** [comment]
What shows up in the send later column? Does it show the scheduled send time, or a message about encryption? Does the message have correct `x-send-later-*` headers? And what is the value of the `content-type` header?

I'm busy the next couple of weeks, but I'll have a look at this as soon as I get a chance. In the mean time, any clues you can gather about what is happening would be helpful.

**Comment by farfallosa** [comment]
In the sen later column the date-time is visible (not encrypted as before) - so that looks pretty good. 
The `x-sind-later-*` looks like this:
```
X-Send-Later-Uuid: {dea2d56f-02f0-40ea-a7b2-f3c3bc897c43}
X-Send-Later-At: Sun, 26 Sep 2021 20:49:00 +0200
X-Send-Later-Recur: none
X-Enigmail-Draft-Status: N00200
X-Mozilla-Draft-Info: internal/draft; vcard=0; receipt=1; DSN=0; uuencode=0;
 attachmentreminder=0; deliveryformat=4
```
The `content-type` header looks like this:
`Content-Type: multipart/encrypted;`

Although I have chosen to send without encryption and subject without encryption and also without pgp signature it seems, that the mail nevertheless does:

**Comment by jph-sendlater** [comment]
I'm surprised the send later column displays the scheduled date and time. In general, it looks for the word "encrypted" in the content-type to figure out whether the message is sendable. If not, it should show the "encryption incompatibility ..." message, as before.

Again, it will be like two weeks before I get a chance to look into this, but I'll let you know if I think of anything to check or try before then.

**Comment by farfallosa** [comment]
Since I the recent TB Update (91.1.2) Send Later works. (I cannot say, however, whether there is a direct connection). 
What becomes apparent, though, emails sent with Send Later loose openpgp signature (this is a minor inconvenience, but may be this is a nice to have fix in future. )
So thanks for your response!

**Comment by jph-sendlater** [comment]
Glad to hear that it's working now.

It hadn't occurred to me before, but losing the signature is unavoidable for the time being. The problem is that before Send Later processes a message, it drops a bunch of intermediary headers (all of the `x-send-later-*` schedule headers), and it also updates the `Date` header. Monkeying with headers like that would make the signature invalid, and it would need to be signed again before finalizing the send process.

So, even though it sounds more trivial than full encryption, it's at least as challenging as full encryption capability. I say "at least" because encrypting a message only requires the recipient's public key, but signing requires access to your own private key. Presumably, once Thunderbird implements an API to enable PGP access from extensions, both of these features will become possible. Until then, we're limited to only sending plain messages via Send Later.
