### ISSUE TITLE
Sending later to an adress list does not work

### ISSUE THREAD

**Issue by Hotkeyharry** [Extended-Thunder/send-later#39]
Hi Jerry, nice add-on, I'm using it for a long time - but: after last update (8.0.3) sending (later) to an address list does not work anymore, only to single adress, any idea, how to fix it, best regards

**Comment by jperryhouts** [comment]
This should be fixed in the latest release: https://github.com/Extended-Thunder/send-later/releases/tag/8.0.7
As mentioned in #29 there seems to be an unusual Thunderbitd behavior about not always properly expanding lists, but version 8.0.7 attempts to workaround that.

I'm going to close this issue for now, but let me know if that does not solve your problem and I'll reopen it.
