### ISSUE TITLE
Time Schedule Changed

### ISSUE THREAD

**Issue by uvtechnolab-git** [Extended-Thunder/send-later#401]
When we select date from date picker it changed automatically.

**Comment by jph-sendlater** [comment]
I've had similar reports from a few users now. Can you give me any more details about this issue? Does it happen all the time? Is there a pattern to which date it randomly changes to? What date/time format do you use (mm/dd/yyyy or dd/mm/yyyy or other)? do you use a custom date/time format (from the Send Later preferences)?

**Comment by jph-sendlater** [comment]
See #409

**Comment by jikamens** [comment]
It took me pretty much all day today, but I believe I both figured out the root cause of the text box and the date picker being out of sync with each other with regards to the proper date format, _and_ figured out a fix that should work for most people. I've implemented that fix in [release 10.0.5](https://github.com/Extended-Thunder/send-later/releases/tag/v10.0.5). If you'd like you can download the pre-release from there and confirm that it fixes the problem for you. In fact, I'd **really** appreciate it if you did that, because I'd like confirmation that the fix actually works before I post the release to addons.thunderbird.net.

You can download the XPI file from the release page and then open the add-ons page in Thunderbird, click on the gear icon, select 'Install add-on from file", and browse to the downloaded XPI file.

I've also documented this problem in detail and how to work around it using a custom date format for the rare cases in which the fix I just implemented doesn't do the trick. See the [user guide](https://extended-thunder.github.io/send-later/#date-format-problems).
