### ISSUE TITLE
Send-Later drafts of a certain size causing Thunderbird to crash

### ISSUE THREAD

**Issue by j-haigh** [Extended-Thunder/send-later#408]
I'm encountering a new issue in which Thunderbird crashes every time I try to open the draft folder in which I have emails set to send later that are of "a certain size". I know that's pretty vague but here's what I know:

- If the draft messages have a couple of images attached or inline (in this case the total size of the images is about 500kb) and I open the draft folder and attempt to click on any given message, Thunderbird crashes.
- Thunderbird does not crash if the "send-later" messages in the draft folder are text-only. This made me wonder if the issue was related to do with having any image attached or inline, so I did a test with a small 1kb image attached. In that case, Thunderbird does NOT crash if the draft messages include an image of that size.  This leads me to believe that it's not specifically to with attachment/no attachment, but rather that there is some kind of a memory or size-related threshold that is causing this issue.

For context, I am using Send-Later in conjunction with Mail Merge so I have a number of draft emails set to be sent later, but this issue seems to persist regardless of the number of emails in the draft folder. Also, I have used send-later in conjunction with mail merge to send emails with images and attachments before, and I have never had this issue.

It's also important to note that I was able to narrow it down to the issue being related to Send-Later, as the issue disappears once I disable Send-Later, even with the same draft emails in the draft folder.

I hope that's more or less clear. If you need any other information from me, please let me know!

**Comment by j-haigh** [comment]
ps. I was able to recreate the crashes using different email accounts with different providers so it's definitely not a server-side issue causing the crashes.

**Comment by jph-sendlater** [comment]
Sorry for the delay responding. I've been busy with a new job, and haven't had much time to devote to Send Later.

I don't know why this would be happening, but I've heard from a few people recently with problems related to performance when they interact with scheduled messages in the Drafts folder. I'm looking into that, and I'll keep you updated when I find the cause.

In the mean time, it *might* help to try disabling the "Show Send Later Column" and "Show Send Later Header" preferences. If that does help, let me know, because it would be a helpful clue about what might be going on.

**Comment by jikamens** [comment]
@j-haigh is this issue still reproducible for you?
