### ISSUE TITLE
Send later dialog box does not work with touch screen

### ISSUE THREAD

**Issue by sometimegithubuser** [Extended-Thunder/send-later#416]
Send Later works fine with mouse clicks, but on a Lenovo Yoga C920 with a touch screen, the pop-up that appears after pressing Send on a new message does not accept touch input. All other function in Thunderbird accept touch input as far as I can tell. If I touch Send on a new email , the Sent Later pop-up appears But when I touch e.g., 'Send Now,' the pop-up just closes. If I touch Send on the email and touch Send now on the popup enough times, three or four, TB partially hangs and I have to exit it. If I use the mouse pad to click on "Send Now" it works fine. 

TB 91.4.1
Send Later 9.0.9
Windows 10 21H2 fully patched. 
Lenovo Yoga C920

This has been an issue for many months.

**Comment by jph-sendlater** [comment]
Sorry for the delay responding to this. I have a bit of a back log of issues here. These sorts of UI issues are not something that extensions can control. You'll have to file a bug against Thunderbird itself, I'm afraid.

**Comment by sometimegithubuser** [comment]
Thanks for the response and the explanation.

**Comment by sometimegithubuser** [comment]
I logged https://bugzilla.mozilla.org/show_bug.cgi?id=1753845 with Thunderbird, but they closed it, saying it's not a TB pop-up so TB can't be responsible. 

How can we move forward on this?

**Comment by jph-sendlater** [comment]
The Thunderbird devs aren't very helpful when the name of an extension comes up, because sorting out what's going on might involve looking into someone else's code, which could be a hassle. I don't really blame them, but it is frustrating when that happens. Extensions have almost no control over rendering anything, so I'm surprised they punted on this one without looking into it at all.

I added a comment that hopefully clarifies the problem for them. Hopefully they open it back up. If they don't re-open the bug in the next few days, you could file a new bug explaining that the issue is with a `composeAction` popup. That would probably get more traction.

**Comment by sometimegithubuser** [comment]
Thanks for the help! Greatly appreciated. I'll look for this to be re-opened on Bugzilla and re-submit if not with the info you supplied!
