### ISSUE TITLE
Email send already read

### ISSUE THREAD

**Issue by ftorrini67** [Extended-Thunder/send-later#417]
Hello, I’m using Send Later and it’s working fine, but, there is just a little mistake, when I send an email, it arrive to destination inbox already read…

**Comment by jph-sendlater** [comment]
When you have a chance, could you try sending a message using the built-in "send later" function? (i.e. use the "Put in Outbox" button in the scheduler dialog, then use "`File > Send Unsent Messages`" to send it. Does that message arrive in an already "read" status?

**Comment by ftorrini67** [comment]
Ok, it works fine, but the message was sent immediatly and not after "X" minutes

**Comment by jph-sendlater** [comment]
I was asking because I'm trying to track down where this is happening. When you sent the message that way, did it arrive already "read"?

**Comment by ftorrini67** [comment]
Yes, this is my step.
1) write a new message
2) press send later button
3) chose one of the option to send "X" minutes later
4) the message stay in draft and then was sent
5) the message arrive to destination already read

I use two different email address in from and to fields, not the same

**Comment by jph-sendlater** [comment]
Yes, but when you did the steps above (put in outbox, file > send unsent messages), did the message arrive already read?

**Comment by ftorrini67** [comment]
If I put message in outbox and then press file->send unsent messages, it works fine, but, of course, TB send immediatly my message and I don't want it

**Comment by jph-sendlater** [comment]
You never answered my question: When you use the "Put in Outbox", `File` > `Send unsent messages` method, does the message appear already "read"?

**Comment by ftorrini67** [comment]
Hello, the answer is on the previous post. No, don't appear already read, but TB send immediatly the message and this is not the desired behavior

**Comment by shmu26** [comment]
I have this same issue. Thunderbird 91.11.0 (64-bit)
running on Windows 11

I did like you wrote before
"When you have a chance, could you try sending a message using the built-in "send later" function? (i.e. use the "Put in Outbox" button in the scheduler dialog, then use "File > Send Unsent Messages" to send it. Does that message arrive in an already "read" status?"

And the result is that it arrives unread, and it stays unread until it is actually read, as expected.

But when I send by clicking twice on the big bar in the extension's menu that shows the selected time to be sent, this is the behavior:
1 It goes into the drafts folder, marked unread
2 At the proper time, it sends, and is deleted from the drafts folder
3 It arrives in Inbox, and after a second, it turns to "read" all by itself, even if I don't read it.

**Comment by jph-sendlater** [comment]
Thanks for the more informative description @shmu26. That is very weird behavior. When send later moves the message from Drafts to the Outbox, it strips all the custom headers, so it shouldn't look any different from any other message. I will follow up with thunderbird devs about it and see if I can track down any clues.

**Comment by jph-sendlater** [comment]
I realized while working on the latest version why this might be happening:
In the past, when you schedule a message it would mark it as "read" in your drafts folder. It did that by taking note of the message id when you compose the message, then waiting for a message with that id to show up in a folder and marking it as "read". However, at some point thunderbird changed so that saving a draft stopped triggering the "new mail" event. So SendLater was still maintaining a list of "messages to mark as Read", but they were never being acted on. But if you sent a message to yourself, it would trigger that event, and SendLater would immediately mark it as "read".

That assumes this was only happening on messages sent to yourself. If it happened on other peoples machines that would be a different story.

Anyhow, that should be fixed in the next beta version (v9.2.1), so hopefully this resolves itself after that. Once that version gets officially released please check with the new version and let me know if this is still happening. Otherwise I'm going to close this issue for now.
