### ISSUE TITLE
Strange bug that switches day and month

### ISSUE THREAD

**Issue by tkoeck** [Extended-Thunder/send-later#429]
![Send_Later_Bug_Report](https://user-images.githubusercontent.com/42435353/156844426-ec015360-ecb8-45d0-aea4-d0c7088be84e.png)

I wanted to send later an email for the 5th March at 00:01 o'clock. That works fine until I re-edit it. Then it switches to 3rd May but the setup still shows the 5th March. See attachment for further information.

I use the newest prod Thunderbird for Windows 10 and perhaps if that might a help, I use a German Windows with German settings and the US Thunderbird. Maybe there is a strange bug where it changes day and month for Non-English users?

**Comment by tkoeck** [comment]
![Send_Later_Bug_Report](https://user-images.githubusercontent.com/42435353/156845173-b9aa1b8a-c9df-4207-aea7-0990abd0fee0.png)

Sorry that is the right screenshot. It seems to happen right after I reedit it.

**Comment by jph-sendlater** [comment]
It sounds like you're having the same issues as #433 . It sounds like defining a custom date/time string in the options helped in their case. Give that a try and let me know what happens.

**Comment by tkoeck** [comment]
Thanks for the answer. I'll look into it and will give feedback.

**Comment by tkoeck** [comment]
I looked into it. Unfortunately, I didn't find examples of how to set it up. The custom date/time option isn't explained in the documentation.

**Comment by jikamens** [comment]
@tkoeck Please see https://support.mozilla.org/en-US/kb/customize-date-time-formats-thunderbird . I'm going to leave this issue open because we really should try to figure out a better way to handle this automatically, but in the meantime, hopefully that article will point you in the right direction for a workaround.

**Comment by jikamens** [comment]
Oh, never mind my previous comment. I see that we were actually talking about configuring a custom date format within Send Later itself.  Yeah, I see that functionality isn't currently documented. I will see what I can do about that. Not sure when I'll get to it, though, since there's a big backlog of issues I'm trying to clean up and my time to work on this is unfortunately limited.

**Comment by lormaccone** [comment]
> ![Send_Later_Bug_Report](https://user-images.githubusercontent.com/42435353/156844426-ec015360-ecb8-45d0-aea4-d0c7088be84e.png)
> 
> I wanted to send later an email for the 5th March at 00:01 o'clock. That works fine until I re-edit it. Then it switches to 3rd May but the setup still shows the 5th March. See attachment for further information.
> 
> I use the newest prod Thunderbird for Windows 10 and perhaps if that might a help, I use a German Windows with German settings and the US Thunderbird. Maybe there is a strange bug where it changes day and month for Non-English users?

I confirm the same bug for an Italian setup (on gentoo linux). The first time you "send later" the correct date appears in the first box as in the first reporter's screenshot. If you then edit the message and try to "send later", the date appears with day and month switched (with carryover if the day>12).

**Comment by Geremia** [comment]
I get an even stranger mismatch in the dates fields:

<img src="https://i.stack.imgur.com/5YT1e.png" width="500"/>

**Comment by jikamens** [comment]
This should be fixed in the [10.0.5 prerelease](https://github.com/Extended-Thunder/send-later/releases/tag/v10.0.5) or in any newer release.

There's also documentation about this in the [user guide](https://extended-thunder.github.io/send-later/#date-format-problems) now, though it won't actually be correct until I ship the next release, i.e., that documentation is accurate for the pre-release, but not for what's on addons.thunderbird.net.

**Comment by Geremia** [comment]
@jikamens Yes, it works for me now. The "Send at…" button now says (in my local language): "4.4 ore da addesso". Was it a localization issue?

**Comment by jikamens** [comment]
The problem arose when there was a mismatch in date formats between the locale configured for the user interface in Thunderbird and the locale configured for date formatting in the operating system. The add-on now uses the operating system date locale in some places where it was previously using the UI locale, which fixes this issue most of the time. It can still happen in some rare cases, though, hence the user guide section referenced above which explains how to work around it.
