### ISSUE TITLE
Make quick action keyboard shortcuts more configurable to work around conflicts with other add-ons

### ISSUE THREAD

**Issue by jamesquilty** [Extended-Thunder/send-later#435]
I have customised the BusinessHours function and set it as the Send Later default. Most of the time my Send Later workflow is:

1. Press `cmd`-`shift`-`return` to send later
1. Scheduling dialog appears with button `Send according to function "BusinessHours"`
1. Press `cmd`-`return` or click-through the scheduling dialog.

It would be extremely rare prior to step 1 for me to not know whether I want to send using my default BusinessHours function or send later at a different time. Most of the time steps 2 and 3 are unnecessary friction in my workflow.

Would it be feasible to implement an additional keyboard shortcut which bypasses the scheduling dialog and acts as if the `Send according to default function` button had been clicked?

If no default function has been defined then the scheduling dialog with an appropriate "no default function set" message would be displayed.

**Comment by jph-sendlater** [comment]
You can assign custom actions in the add-on preferences:
![image](https://user-images.githubusercontent.com/75693008/163698633-acbf6178-bc02-4183-9931-6bfa87f5c073.png)

Check out this documentation for info on how to use that: https://extended-thunder.github.io/send-later/#shortcut-buttons

In short, if you set the first shortcut button to "Business Hours", with your preferred arguments, then you can execute it directly from the message compose window with `Ctrl+Alt+1`

**Comment by maxmichels** [comment]
@jamesquilty then use it as shortcut 2 and use ctrl+alt+2?! ;-) Then you can use the current add-on with the 1 and BusinessHours on the 2...

**Comment by jamesquilty** [comment]
@maxmichels all of the `control-option-<number>` combinations are bound by the other add-on. As an unused-by-the-OS combination, there's inevitable competition and conflict over `control-option` combinations.

**Comment by jikamens** [comment]
@jamesquilty if Send Later let you configure the key to hit with Ctrl-Alt to activate each of the three shortcuts would that be sufficient so solve this problem for you?

**Comment by jamesquilty** [comment]
@jikamens yes, thanks, I think that would be sufficient!

**Comment by jikamens** [comment]
This issue should be fixed in release 10.2.4 of Send Later.

To check what version of Send Later you have:

* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Extensions on the left if you're not already on the left if you're not already there.
* Find Send Later in the list of extensions and click on it to open its details page.
* The version number should be displayed there next to
"Version".

This release is not yet available for download from addons.thunderbird.net, but you can download and install it from its [GitHub release page](https://github.com/Extended-Thunder/send-later/releases/tag/v10.2.4) as follows:

* Download [send_later.xpi](https://github.com/Extended-Thunder/send-later/releases/download/v10.2.4/send_later.xpi) to your computer. (If you are using Firefox, make sure to right click on the link and select
"Save Link As..." rather than just clicking on it, because otherwise Firefox will try to install it as a Firefox add-on.)
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click the gear icon at the top and select "Install Add-on From File...".
* Browse to and select the downloaded file.
* Click through the installation pop-ups.
* You can delete the downloaded file once you've installed it into Thunderbird.

To subscribe to future beta releases (we love beta testers!), download and install [send_later_beta.xpi](https://github.com/Extended-Thunder/send-later/releases/download/v10.2.4/send_later_beta.xpi) instead. The advantage is that if there's a bug that affects your workflow you'll help find it and get it fixed quickly. The disadvantage is that bugs are a bit more likely in beta releases. You can unsubscribe from beta releases at any time by downloading and installing send_later.xpi or installing from [addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/).

Note that this is a prerelease. While we make every effort to ensure that prereleases are stable, they are a bit more likely to have bugs, so proceed with caution.

If you prefer to wait, the release will eventually be available on addons.thunderbird.net, and unless you've turned off automatic add-on updates, Thunderbird will eventually update to the new version automatically. To update immediately once it's available:

* Go to [addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/versions/) and confirm that release 10.2.4 is available for download there.
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Send later.
* Click the gear icon and select "Check for Updates".
* The add-on should update and then you should see the message, "Your add-ons have been updated," next to the gear icon.

Please let me know if you still see this issue in this release.
