### ISSUE TITLE
send later not working on mac

### ISSUE THREAD

**Issue by pauldevos1969** [Extended-Thunder/send-later#436]
I have installed the add-on on the latest version of thunderbird on my macbook pro. The emails are put in my draft folder but never send. Anybody any idea what I can do? I do have the normal screen where I can select the send time and date but they never leave my draft folder. In advance many thanks for your suggestions

![Naamloos 2](https://user-images.githubusercontent.com/102162437/159494908-ef824618-789b-4c38-b3a7-30db68fd6261.jpg)

![Naamloos 2](https://user-images.githubusercontent.com/102162437/159494750-b7f32f32-b96e-413a-a1a2-1ac8255920b3.jpg)

**Comment by despecial** [comment]
My problem is a bit different but also on a Mac

I scheduled a message for this morning and let my machine in standby mode (new M1)
After I checked Thunderbird, it is stuck in "Outbox" folder and there is no option to force the send.
Autmatically delay is set to 10min but still, nothing is sent

**Comment by jph-sendlater** [comment]
@despecial Send Later can't work when your computer is not awake. It needs to be actively running at the time when the message is due to be sent. When messages are in your Outbox, you can send them manually with "File > Send Unsent Messages"

@pauldevos1969 There are some suggestions on where to start troubleshooting in the documentation here: https://extended-thunder.github.io/send-later/#messages-dont-send-or-send-multiple-times
Please work through those steps and let me know what you find

**Comment by despecial** [comment]
@jph-sendlater I understand when in standby mode (on new M1s) it doesnt work.
But even after the machine was unlocked and in working mode it wasnt sent out and stuck in the outbox folder (schedulded time was 1 hour before)

**Comment by jikamens** [comment]
@despecial, @jph-sendlater already answered your question. When your computer came back on Send Later attempted to send the message and put it into your Outbox, but it doesn't be delivered because your network hadn't come back up yet. You need to do File > Send Unsent Messages to tell TB to send the unsent message. At that point it's out of Send Later's hands. In any case your issue is not the same as the issue reported here, so please don't clutter up this issue with further discussion of your issue.

@pauldevos1969 are you still having this problem?

**Comment by jikamens** [comment]
Closing because no response and I believe this is fixed in Send Later 9.3.0 or 10.0.1. If you're still seeing the issue in one of those versions or a newer one, feel free to reopen or comment on this issue or open a new one as you prefer.
