### ISSUE TITLE
If you ESC from the Send Later Window and you click the button again nothing appears

### ISSUE THREAD

**Issue by andreamoretti** [Extended-Thunder/send-later#472]
Hello,
imagine this scenario:
- you write a mail
- you click the send later's button
- you discover a typos then you esc the send later's window
- you click again the send later's button: now the windows is empty.

The only way to resolve is close the mail saving as draft and open it again.

This occurs 100% times.

Ciao e grazie

Andrea Moretti

**Comment by jph-sendlater** [comment]
That sounds like a Thunderbird issue, since Send Later isn't responsible for actually rendering the popup action contents.

I can't reproduce it locally, so it's possible that something in the latest beta version of thunderbird already fixed it. I'll leave this open as a reminder and check in about it down the road to see if it's been resolved.

**Comment by jikamens** [comment]
This happens to me on macOS but not Linux.

**Comment by jph-sendlater** [comment]
Second report of this happening from @jikamens this time with latest SL beta. I still can't reproduce it locally. Can either of you give any more detailed debugging info (Thunderbird version, OS, other extensions, etc)?

**Comment by andreamoretti** [comment]
I use Thunderbird 102.4.2 (64 bit) with the following extensions:
AttachmentExtractor Continued
ImportExportTools NG
Manually sort folders
Xpunge

and, of course, Send Later... ;-)

**Comment by jikamens** [comment]
@andreamoretti are you still seeing this issue?

**Comment by andreamoretti** [comment]
No, the issue has been solved.

Thank you!


> @andreamoretti are you still seeing this issue?
