### ISSUE TITLE
Delivery Status Notification and Return Receipt are knowingly ignored, user not notified

### ISSUE THREAD

**Issue by AGI-chandler** [Extended-Thunder/send-later#509]
I recently sent an extremely important e-mail which required the use of Return Receipts (i.e. adding Disposition-Notification-To header) and Delivery Status Notification (receiving back the success/failure of delivery from the SMTP server).  Yet, I received no responses.  I realize these extra options can be ignored by some servers and the recipients, but to receive back 0 responses seemed off.  After several hours of research and testing, I found that Send Later was responsible, and simply ignores these options if they are activated by the user.  I use the "Send delays messages by X minutes" option in case I miss something last second and need to cancel sending the message.  Using this option, or scheduling the e-mail to be sent at a later time, ignores these options if activated by the user.  The user is not notified of this change to their e-mail at all.

What's even more frustrating, is [you've been aware of this since at least TB 78, as mentioned on your blog](https://blog.kamens.us/send-later/#receipt).  Although this doesn't mention that Delivery Status Notification is also ignored.

I understand these options are rarely used, but when they are used, it's typically for something of high importance.  I also understand that these options are difficult to make work with Send Later, and it's fair that you don't support them.  However, you really should put more effort into making the user aware of this.  For example, after installing the add-on, I was never directed nor shown [the homepage](https://extended-thunder.github.io/send-later) nor [the wiki](https://github.com/Extended-Thunder/send-later/wiki), where this altering of my e-mails is mentioned in the `Caveats and known issues` section.

Further, when an e-mail is scheduled to be sent, I think you could perform an additional check on the e-mail to see if it has either the Return Receipt or Delivery Status Notification option activated.  If so, show a warning dialog box to the user explaining these options will be ignored, plus a link to the `Caveats and known issues` section with further details, and a checkbox to "don't warn me again about this" for example.

Now the whole procedure has been permanently ruined.  I guess I'll have to send the same e-mail again with Send Later disabled to at least have some semblance of followed procedure with evidence of the results... but now the recipients will have two copies of the e-mail, causing confusion and broken threads of replies, among other things.  It's just a big mess now.

**Comment by jikamens** [comment]
While I do understand your frustration here, I want to point out that the fact that return receipts and DSNs don't work for Send Later is actually a Thunderbird bug, not a Send Later bug.

Having said that, in the next Send Later release, return receipts will work (I came up with a workaround) and Send Later won't let you schedule a message if you have DSN turned on, since there's no way I can make that work.

**Comment by jikamens** [comment]
This issue should be fixed in release 10.2.0 of Send Later. To check what version of Send Later you have:

* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Extensions on the left if you're not already on the left if you're not already there.
* Find Send Later in the list of extensions and click on it to open its details page.
* The version number should be displayed there next to
"Version".

This release is not yet available for download from addons.thunderbird.net, but you can download and install it from its [GitHub release page](https://github.com/Extended-Thunder/send-later/releases/tag/v10.2.0) as follows:

* Download [this file](https://github.com/Extended-Thunder/send-later/releases/download/v10.2.0/send_later.xpi) to your computer. (If you are using Firefox, make sure to right click on the link and select
"Save Link As..." rather than just clicking on it, because otherwise Firefox will try to install it as a Firefox add-on.)
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click the gear icon at the top and select "Install Add-on From File...".
* Browse to and select the downloaded file.
* Click through the installation pop-ups.
* You can delete the downloaded file once you've installed it into Thunderbird.

Note that this is a prerelease. While we make every effort to ensure that prereleases are stable, they are a bit more likely to have bugs, so proceed with caution.

If you prefer to wait, the release will eventually be available on addons.thunderbird.net, and unless you've turned off automatic add-on updates, Thunderbird will eventually update to the new version automatically. To update immediately once it's available:

* Go to [addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/versions/) and confirm that release 10.2.0 is available for download there.
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Send later.
* Click the gear icon and select "Check for Updates".
* The add-on should update and then you should see the message, "Your add-ons have been updated," next to the gear icon.

Please let me know if you still see this issue in this release.
