### ISSUE TITLE
Enable claiming drafts scheduled by another client

### ISSUE THREAD

**Issue by Davidholland1** [Extended-Thunder/send-later#513]
I have used send later a few times and I find it extremely useful however I am running an issue. I scheduled some email to send later from a different client (office pc) and when home I turned on on my home computer it says "Scheduled by another client"

I can click on each email individually to schedule for later but cant do it all together as I have around 20 email schedule and individual scheduling again will take more time. 

Sorry for naïve question but I will appreciate your reply. Thanks

**Comment by jph-sendlater** [comment]
That's an important feature because if both your work PC and home PC were running at the same time, it would be possible that both computers attempt to send the same message simultaneously. When you schedule a message it's locked to the PC on which you scheduled it. I will keep this issue open as a feature request to enable "capturing" the existing scheduled messages, but it's unlikely I'll have a chance to do that very soon.

In the mean time if you are positive you will never have both PC's running simultaneously, it's possible to work around this by going into the "Advanced configuration editor" in Send Later' preferences (see screenshot) and set the "InstanceUUID" to the same value on both PC's. Note it doesn't really matter what value you put there, it just needs to be identical. But please be 100% sure you understand the consequences of doing that. If you ever leave Thunderbird running on both PC's you might end up sending duplicates of your scheduled messages.

![image](https://user-images.githubusercontent.com/75693008/212495738-4e6dd492-f150-49be-b3d4-c95f91875471.png)

**Comment by Davidholland1** [comment]
Great ! Thank you so much for the help. I will try that out and share the results here. For clarity the condition previously was 1 PC was running at a given time. Some email sent from work pc some were scheduled for off the work hours so I tried to continue on home PC.

**Comment by Davidholland1** [comment]
I changed the instanceUUID of my one PC to be the same as my home PC. Now I am scheduling emails on my work PC but it says "Scheduled by another client" when the client is same. Emails are not sent either and are stuck in drafts. @jph-sendlater

**Comment by jikamens** [comment]
@Davidholland1 is this still an issue? If so can you cut/paste the advanced config settings JSON from both PCs into a comment in this ticket? (Please quote them as code. If you're not familiar with how to do that, please click on the markdown button at the bottom right corner of the comment box to view Markdown formatting instructions and see the "Quoting code" section (https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code).

**Comment by jikamens** [comment]
This issue should be fixed in release 10.2.0 of Send Later. To check what version of Send Later you have:

* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Extensions on the left if you're not already on the left if you're not already there.
* Find Send Later in the list of extensions and click on it to open its details page.
* The version number should be displayed there next to
"Version".

This release is not yet available for download from addons.thunderbird.net, but you can download and install it from its [GitHub release page](https://github.com/Extended-Thunder/send-later/releases/tag/v10.2.0) as follows:

* Download [this file](https://github.com/Extended-Thunder/send-later/releases/download/v10.2.0/send_later.xpi) to your computer. (If you are using Firefox, make sure to right click on the link and select
"Save Link As..." rather than just clicking on it, because otherwise Firefox will try to install it as a Firefox add-on.)
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click the gear icon at the top and select "Install Add-on From File...".
* Browse to and select the downloaded file.
* Click through the installation pop-ups.
* You can delete the downloaded file once you've installed it into Thunderbird.

Note that this is a prerelease. While we make every effort to ensure that prereleases are stable, they are a bit more likely to have bugs, so proceed with caution.

If you prefer to wait, the release will eventually be available on addons.thunderbird.net, and unless you've turned off automatic add-on updates, Thunderbird will eventually update to the new version automatically. To update immediately once it's available:

* Go to [addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/versions/) and confirm that release 10.2.0 is available for download there.
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Send later.
* Click the gear icon and select "Check for Updates".
* The add-on should update and then you should see the message, "Your add-ons have been updated," next to the gear icon.

Please let me know if you still see this issue in this release.

**Comment by jikamens** [comment]
**Beware,** however, that if the accounts configured into the two Thunderbird instances don't exactly match, you may see unpredictable behavior including Send Later messages getting sent out through the wrong mail servers. See [the user guide](https://extended-thunder.github.io/send-later/#matching-accounts) for more on this and what to do about it.

**Comment by jikamens** [comment]
OK, so I figured out how to fix the issue in the previous comment. Try this version instead:

This issue should be fixed in release 10.2.1 of Send Later. To check what version of Send Later you have:

* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Extensions on the left if you're not already on the left if you're not already there.
* Find Send Later in the list of extensions and click on it to open its details page.
* The version number should be displayed there next to
"Version".

This release is not yet available for download from addons.thunderbird.net, but you can download and install it from its [GitHub release page](https://github.com/Extended-Thunder/send-later/releases/tag/v10.2.1) as follows:

* Download [this file](https://github.com/Extended-Thunder/send-later/releases/download/v10.2.1/send_later.xpi) to your computer. (If you are using Firefox, make sure to right click on the link and select
"Save Link As..." rather than just clicking on it, because otherwise Firefox will try to install it as a Firefox add-on.)
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click the gear icon at the top and select "Install Add-on From File...".
* Browse to and select the downloaded file.
* Click through the installation pop-ups.
* You can delete the downloaded file once you've installed it into Thunderbird.

Note that this is a prerelease. While we make every effort to ensure that prereleases are stable, they are a bit more likely to have bugs, so proceed with caution.

If you prefer to wait, the release will eventually be available on addons.thunderbird.net, and unless you've turned off automatic add-on updates, Thunderbird will eventually update to the new version automatically. To update immediately once it's available:

* Go to [addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/versions/) and confirm that release 10.2.1 is available for download there.
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Send later.
* Click the gear icon and select "Check for Updates".
* The add-on should update and then you should see the message, "Your add-ons have been updated," next to the gear icon.

Please let me know if you still see this issue in this release.
