### ISSUE TITLE
Send Message Error after Send Later

### ISSUE THREAD

**Issue by eibyer** [Extended-Thunder/send-later#538]
I have a strange error that pops up after each Send Later task. The messages get sent and parts of the error message does not even relate to the email that was originally sent.

Daily Hours Distribution is a distribution email list in my Thunderbird address book. 

![2023-05-02_072112](https://user-images.githubusercontent.com/19540436/235722630-a0523fa3-01c4-4090-80e7-975fb5cb8902.png)

**Comment by jikamens** [comment]
Sorry for the delay getting back to you about this.

Is this still an issue?

Distribution lists are supposed to be expanded when messages are scheduled. I just did a basic test of this functionality and it appears to be working. I.e., I created a message whose recipient list contained a local distribution list, then scheduled the message to be sent 1 minute in the future, then confirmed that the distribution list in the header was replaced with the full recipient list before the scheduled message was saved into the drafts folder.

Is that not the behavior you are seeing? I.e., when you look at the scheduled message in the Drafts folder, do you see "Daily Hours Distribution" one of the recipient headers? Can you open the draft message source with ctrl-U and copy and paste the message header into an email message to me (jik@extended-thunder.org) so I can look at it? Don't post it here since it presumably contains email addresses and other private information.

**Comment by jikamens** [comment]
The message with the bad header is in your Outbox under Local Folders. Deleting it from there should make the problem go away. Feel free to reopen this issue if it doesn't.
