### ISSUE TITLE
bring back SugarJS date parsing

### ISSUE THREAD

**Issue by jikamens** [Extended-Thunder/send-later#54]
Many, many Send Later users prefer to be able to enter the send time by typing it rather than having to use the date/time picker. This is a popular feature of the add-on and it needs to be restored.

**Comment by rgrun1** [comment]
I have become used to the date picker. If you bring back the old way PLEASE have save as default working to eliminate a lot of duplicate typing
Thanks

**Comment by jperryhouts** [comment]
This is fixed by #76 -- but, using moment.js, because I'm already using that for some date formatting elsewhere and I think it's slightly more lightweight than Sugar.js. I don't know if the date parsing ability is identical between the two, but supposedly it's pretty good in moment.js. Let me know if it's missing something important that I'm not aware of.
