### ISSUE TITLE
 that send Later : Folder Drafts  may be corrupt and i have to open its properties and repair it

### ISSUE THREAD

**Issue by RichardPinka** [Extended-Thunder/send-later#545]
Same for me. 
When i started app, i simply just wanted to get send emails with 10 minutes delay (nothing else). 
but application started to inform me , that send Later : Folder Drafts  may be corrupt and i have to open its properties and repair it.  What the hack is this ? 

- application should send email in appropriate time to send it -> it does not do it
- application should wait, if my internet connection and thunderbirt  is off (in time when i am using mobile phone for calling) - it does not doing it, it just starts panic
- application should evaluate, if time of sending already passed (for example i turn pc off sooner, that email is send) and quietly send the email , or wait, till internet connection will be setup and send email - it does not doing it

![chyba send later 2](https://github.com/Extended-Thunder/send-later/assets/8267708/42220482-c936-45ad-bf59-f4ed0c744361)

**Comment by jikamens** [comment]
I apologize for the delay getting back to you about this.

The add-on is behaving correctly here. It has detected corruption and is telling you what to do to fix it. If you haven't followed the instructions to repair your Drafts folder, then you should do that. If you've done that and the problem recurs, then your Drafts folder is getting corrupted repeatedly. This is a problem which does seem to happen to some people more than others, but we've never been able to determine the root cause, and _it is not a Send Later issue_, it's an issue with the underlying Thunderbird folder handling. There's nothing Send Later can do about it except to display the message when it detects the problem.
