### ISSUE TITLE
Another "no longer works" 

### ISSUE THREAD

**Issue by jkohan0** [Extended-Thunder/send-later#549]
Hello. I have a recurrent mail programmed for today, and it didn´t fire. Maybe my laptop was suspended at the moment it had to be sent this morning. I allow for more than 10000 minutes of delay, so that time isn´t expired. 
I´ve even tried closing and opening Thunderbird at all, but neither that worked. 
I cannot see any errors at UI. 
What else can I check ? 
Thanks
(102.12.0 (64-bits) - Win 11 Pro)

**Comment by jikamens** [comment]
Sorry for the delay getting back to you about this, we're a bit short-staffed at the moment. Is this still a problem?

**Comment by jkohan0** [comment]
Hello. Yes. I just tried a message with 5 min delay and it didn´t work. My laptop was active and Thunderbird open all the time but the message wasn´t sent. I can see it in Drafts whith the correct time to be sent. 

Thanks.

**Comment by jikamens** [comment]
Please follow the instructions at https://extended-thunder.github.io/send-later/#debug-logging for capturing debug logs to help me troubleshoot this issue. Before you start, make sure you have a scheduled message in your Drafts folder with a scheduled time before the current time. Then, at step 5 in those instructions, please wait at least two minutes (assuming that you have Send Later configured to the default of checking for scheduled messages once per month) and then proceed with the rest of the instructions. You can email me the log at jik@kamens.us rather than posting it here since it may contain private-ish information.

**Comment by jkohan0** [comment]
Some minutes ago I sent what you requested.  Let me know if I you need me to check something else
Thanks
Javier

**Comment by jikamens** [comment]
I think this is probably because of the bug described in #529. We have a fix but it hasn't been released yet. Let's revisit and confirm it's working again for you after that fix is released.

**Comment by jikamens** [comment]
If you are using TB109, please check if this is still and issue with version 9.3.0 (or newer) of the add-on.

If you are using TB115, please install version 10.0.1 of the add-on, which will appear on addons.thunderbird.net shortly (I just uploaded it), and check if it is still an issue.

If you are still seeing the issue with 9.3.0 or 10.0.1, please reopen this issue or comment if GitHub won't let you reopen it.
