### ISSUE TITLE
[Dev] Suggestion to drop message header Experiment and display send later info as a banner at the top of the message

### ISSUE THREAD

**Issue by jobisoft** [Extended-Thunder/send-later#556]
In order to reduce Experiments and reduce the work needed for add-on maintenance, the header information could be displayed by a message display script.
Example:
https://github.com/thundernest/sample-extensions/tree/master/manifest_v2/messageDisplayScript

![image](https://github.com/Extended-Thunder/send-later/assets/5830621/ddfe6342-a4ca-4143-947e-546514e36323)

**Comment by jobisoft** [comment]
The header area again changed for 115. This move would therefore speed up the add-on update.

**Comment by jikamens** [comment]
This isn't ideal because when multiple banners are being displayed from different sources sometimes not all of them are visible to the user.

I agree that this is a reasonable short-term change if there's a long term plan to restore the ability of add-ons to display custom headers, at which point we can put that functionality back without needing an experiment.

I'm not sure I agree with the proposed change if there's no plan for such an API in the long term.

**Comment by jikamens** [comment]
I think we're going to keep things as-is until support for extra headers is added to the API, so closing this.
