### ISSUE TITLE
SL Column - missing.

### ISSUE THREAD

**Issue by Bluestone357** [Extended-Thunder/send-later#576]
I may be a bit dim...
Upgraded to Tb 115.1.0 and SL 10.0.1

The Send Later column and header have disappeared.
Right click on the column headers no longer offers an SL option.

What am I doing wrong?
Cheers.

![Send Later1](https://github.com/Extended-Thunder/send-later/assets/74246226/e90b02f5-53c9-4616-839b-2b3e75205926)

**Comment by jikamens** [comment]
You're not doing anything wrong. The column is unavailable starting in Thunderbird 115 due to missing functionality in Thunderbird I've [updated the FAQ] (#278) and the [user guide](https://extended-thunder.github.io/send-later/#the-send-later-column-in-the-drafts-folder-message-list-is-missing) to reflect this. There's an [open issue] (#555) about fixing it, once the Thunderbird make it possible for us to do that.
