### ISSUE TITLE
Editing SendLater draft → default settings not loaded

### ISSUE THREAD

**Issue by Geremia** [Extended-Thunder/send-later#589]
Here is what my SendLater popup looks like initially. My default settings are correctly loaded:

<img src="https://i.stack.imgur.com/QtAY9.png" width="500"/>

After hitting the "Send at…" button, which places my email in the drafts folder, then re-editing the email in the draft folder and clicking the SendLater button, here is what is displayed:

<img src="https://i.stack.imgur.com/5YT1e.png" width="500"/>

My default settings are not loaded (the "Recur once" radio button is selected)

Also, there is a strange mismatch in the dates in the date text fields (cf. issue #429).

**Comment by jikamens** [comment]
The behavior regarding the date field mismatch is, as you noted, being addressed in #429.

The other behavior is correct. Once a message has been scheduled using a dynamic scheduling function that doesn't actually have recurrence in it, that scheduling function is no longer applicable, since the scheduled message is a one-time message with a specific date/time scheduled, so the "Recur" setting switches back to "once".

**Comment by Geremia** [comment]
@jikamens 
>so the "Recur" setting switches back to "once".

What does "Save these value as the defaults" save, then?

**Comment by jikamens** [comment]
>What does "Save these value as the defaults" save, then?

It configures the defaults for when you are composing a new draft rather than editing a previously scheduled one.

If you are editing a previously scheduled draft than the defaults are whatever the draft's schedule was before you started editing it.

These seems intuitive to me. :shrug:
