### ISSUE TITLE
Installation of beta picked up ~800 old emails and sent them again

### ISSUE THREAD

**Issue by tplanter** [Extended-Thunder/send-later#59]
Thunderbird updated itself to v78 without me realising. After restarting and realising that a number of extensions were not operating, I installed the SendLater beta, wrote an email. Pressed Send, expecting to see the Sendlater dialog.
This didn't appear, but Thunderbird seemed to be trying to send the email, but taking a long time about it.
I was notified  by a recipient of a few of the additional emails what was happening, so went off line. 
Couldn't shut Thunderbird down because of innumerable dialog boxes about not being able to send, so shut it down via Task Maanager. Restarted Thunderbird while wi-fi was not connected. Was asked if I wanted to send emails in Outbox. Clicked no. Checked the Outbox and there were over 800 emails waiting to go. Deleted all these and disabled SendLater.
Discovered about 60 old emails had been sent.
All is now OK.
I'm not sure if it is a SendLater issue or a Thunderbird issue, but the former seems more likely.

**Comment by jperryhouts** [comment]
This kept me up last night. I don't know why this would happen, but I'm working on it today. In the mean time I took down the most recent beta release until this is figured out.

Can you give me more information about your setup? In particular what system you're on, what sort of email account you're using (IMAP, POP, OWL, etc), your Thunderbird version, and Send Later version (just check the .xpi file name that you downloaded). Were the sent messages ones that had previously been sent by Send Later? Also, do you have any other addons installed? Lastly, is there any possibility these messages started sending before you installed the new Send Later?

This should never have happened. I'm hoping the solution is simple, but right now I don't have a good sense of what could have caused it. I really apologize for the inconvenience.

**Comment by tplanter** [comment]
The setup:

Win10 Pro v2004 OS Build 19041.572

Thunderbird v78.4.0 Build ID20201019003438, updated on the update channel.

I have 1 POP3 account, 6 gmail IMAP accounts.

Add-ons installed are:
    LookOut (fix version),
    Mail Merge,
    Manually sort folders
    Quicktext
    Send Later (now disabled but is send_later-8.0.11-tb.xpi)
    XNote + + (disabled - currently incompatible with V78)
    Show All Body Parts (disabled - currently incompatible with V78)

I am fairly confident that all the sent (or attempted to send) messages were previously sent by Send Later, as I almost always use the 15 minute Send Later delay. There is only 1 recipient I never pass through Send Later, and they did not receive any old messages. Unfortunately, I've deleted the resent messages, so cannot check this properly.

Is there any header that remains in the Sent email when it has been through Send Later?

I'm confident that the messages only started sending after I installed the new Send Later. My reasoning for this is that Thunderbird Update History shows an installation date/time of 28/10/20, 6:33:34 pm.  BUT I didn't note the request to reboot for installation until the next day.

Send Later xpi download date/time is 29/10/2020 9:56pm.

I remember that the earliest of the of the messages was timed as sent at 9:57pm.

I suppose it could be something I did (or didn't) do, but I don't think so. I can't think how to replicate the issue, other than to delete Send Later, then reinstall it and see what happens. I'm a little nervous about doing so, but I could at the least disconnect my computer before installing Send Later.

Do you want me to try? And if I do, what logging, etc do I need to implement to give you the information you need?

**Comment by jperryhouts** [comment]
I discussed this with @jikamens and it sounds like this is related to a Thunderbird bug where corrupted Outbox and/or Drafts folder(s) can cause deleted messages to magically reappear. That's normally just a nuisance if it happens in a regular folder, but it can (clearly) be a disaster if it happens to the outbox, and with Send Later installed it can also be a major problem if it happens with the Drafts folder. The legacy version had two precautions in place to handle this: compacting the outbox after each send, and remembering previously sent messages to prevent re-sending duplicates from the drafts folder (at least within the same Thunderbird session).

I implemented the outbox compaction in 8.0.12 along with some other send-time logic, and since you submitted this bug right after that was released I jumped to the conclusion that was somehow responsible. Rather, what I now think happened was that your drafts folder had become corrupted during the upgrade to TB78. That could have resulted in lots of previously sent drafts reappearing in the message index, being picked up by SL and re-sent.

Since then I added the following additional precautions:
* Next time a user upgrades Send Later it will first compact the outbox and all drafts folders. It will then check whether there is anything in the outbox, and whether there are any pending scheduled messages in Drafts and report those numbers to the user. The user will have the option to either continue on as usual or disable send later (via preferences) until they manually choose to reactivate it.
* By default, the outbox will be compacted after each send operation
* Send Later will maintain a log of all message IDs that have been sent by SL using local storage, and will check each new message against it. It has the advantage of persisting across restarts, which I believe the legacy version did not do. This may prove to be an infeasible solution eventually, as this collection could potentially grow quite large. It should be okay for the time being though.
* In the next release (8.0.16) the default preferences for new installations will block late messages more than 48 hours old. This won't affect existing users unless they change their preferences manually.

At this point I recommend following the instructions for repairing or rebuilding your outbox and Drafts folders: [https://blog.kamens.us/send-later/#corrupt-outbox](https://blog.kamens.us/send-later/#corrupt-outbox), then installing the latest release candidate [v8.0.15](https://github.com/Extended-Thunder/send-later/releases/tag/8.0.15-rc2). I also recommend restarting Thunderbird after installing the new version out of an abundance of caution.

I really apologize again for that. I wish there were more I could do to actually solve this bug, but the root problem is at a much lower level in Thunderbird that addons can't control. I'm hoping these safeguards are enough to catch this situation early and prevent it from doing any damage in the future. I'm closing this issue for now, but let me know once you give the new version a try.
