### ISSUE TITLE
Customized date formats, date-picker in pop-up still using wrong format

### ISSUE THREAD

**Issue by pol-hallen** [Extended-Thunder/send-later#595]
Also fill with these: %d/%m/%Y, %H:%M I've same results :-/ I removed and reinstalled extension but same problem. It happens only with this pc, other works.

Is there any files can I will remove? Maybe sendlater read a wrong config file :-/ 
can you help me? thanks
Pol

PS: circled with black it's correct, with red incorrect :-/

![sendlater2](https://github.com/Extended-Thunder/send-later/assets/67121219/4075593b-61d5-4023-a5c6-5e8f6f62d683)

{
  "checkTimePref": 1,
  "checkTimePref_isMilliseconds": false,
  "quickOptions1Label": "15 minutes from now",
  "quickOptions1funcselect": "Delay",
  "quickOptions1Args": "15",
  "quickOptions2Label": "30 minutes from now",
  "quickOptions2funcselect": "Delay",
  "quickOptions2Args": "30",
  "quickOptions3Label": "2 hours from now",
  "quickOptions3funcselect": "Delay",
  "quickOptions3Args": "120",
  "accelCtrlfuncselect": "Delay",
  "accelCtrlArgs": "5",
  "accelShiftfuncselect": "BusinessHours",
  "accelShiftArgs": "",
  "showHeader": true,
  "showColumn": true,
  "showStatus": true,
  "logConsoleLevel": "info",
  "logDumpLevel": "fatal",
  "logFilter": "",
  "sendUnsentMsgs": true,
  "sendDrafts": true,
  "sendButton": false,
  "sendDoesDelay": false,
  "sendDelay": 10,
  "sendDoesSL": false,
  "showEditAlert": true,
  "showOutboxAlert": true,
  "showSendNowAlert": true,
  "altBinding": false,
  "sendWhileOffline": true,
  "enforceTimeRestrictions": true,
  "blockLateMessages": true,
  "lateGracePeriod": 2880,
  "activeScanner_lastUUID": "{d4f8bfed-33f8-487d-b649-a9c77c118ea1}",
  "activeScanner_UUID": "",
  "activeScanner_time": 1569999627,
  "askTime": 0,
  "askSent": 0,
  "askQuit": true,
  "relNotes": "6.4.6",
  "disabledForEnigmail": false,
  "editorFirstUse": false,
  "promptDefaults": "",
  "markDraftsRead": true,
  "composeWindowHotkeys": true,
  "instanceUUID": "{6128dc74-5ee0-4c40-8fbb-09f1b21d5a17}",
  "throttleDelay": 0,
  "customizeDateTime": true,
  "shortDateTimeFormat": "%d/%m/%Y, %H:%M",
  "longDateTimeFormat": "%d/%m/%Y, %H:%M",
  "migratedLegacy": 7
}

_Originally posted by @pol-hallen in https://github.com/Extended-Thunder/send-later/issues/444#issuecomment-1693095501_

**Comment by jikamens** [comment]
Send Later cannot control the format of how dates are displayed in the date-picker (the thing you circled in red). That is controlled by the language / region operating system settings, not by the custom date formats in Send Later.

When Thunderbird creates the date-picker to display in the pop-up, it tells the operating system to format a sample date, looks at the order of the month and day in the formatted sample, and orders the month and day in the date-picker to match that. If you want to reverse the order of the month and day in the date-picker, you need to change your region in your OS settings to one that uses the desired order. For example, if you've got the OS configured for English, you could configure it to use British or Canadian English instead of American English.

In fact, I suspect American English is the only locale in the world that uses mm/dd/yyyy instead of dd/mm/yyyy. :confused:
