### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by Bluestone357** [Extended-Thunder/send-later#607]
New message:
Send Later can't schedule messages that are encrypted or digitally signed; you must disable these on a draft before you can schedule it. You must also disable “Store draft messages in encrypted format” under “End-To-End Encryption” for accounts or identities for which you wish to schedule messages.

I've changed nothing - apart from update to 10.0.9

Please point me in the direction of a resolution.

**Comment by Bluestone357** [comment]
Hi JK - went to End-To-End...

Is this where I add a Personal Open PGP Key?
The radio buttons for dis/enable encryption are grayed out.

**Comment by nikkisiz23** [comment]
How do we disable what we need to disable.  When I go into settings it is showing as it is already disabled?

**Comment by Onurb31** [comment]
Same error here.
I use TB 102.14.0 (32b).
My accounts are not encrypted. I have generated a OpenPGP key. I have unchecked "save drafts in encrypted formats". I have tried to send emails either by using the OpenPGP identity or not (but not signing or encrypting the messages). The message is saved n the draft folder with an hour corresponding to the hour on which it is to be sent. 
The SL box shows the message. However, it is never sent. I remains in the draft folder.
It is a pity that this error appears with the new update, as everything worked perfectly before this update.

**Comment by nikkisiz23** [comment]
> Sorted. Key generated, applied, published. SL also sends when expected.

What did you have to do to fix this?

**Comment by Bluestone357** [comment]
> Nikkisiz23 - try:
Click on the email address.
End-To-End Encryption on top row.
Generate a Key for OpenPGP
Publish (& confirm when asked via email)
Disable encryption - no longer greyed out.
Uncheck Store drafts in encrypted format.

**Comment by azuredusk10** [comment]
I don't use encryption in any of my emails or accounts, but today I started receiving the same error message whenever I tried to use Send Later after it updated to the latest version. I'm a bit confused why it's showing an error about end-to-end-encryption when I haven't set up anything like that before.

**Comment by jikamens** [comment]
Sorry about this! There's a bug in 10.1.0. I'll be releasing a fix later today.

**Comment by jikamens** [comment]
I have released version 10.1.1 of Send Later which fixes all of the issues people have encountered today. The full list of fixes in this version is viewable on its [GitHub release page][rp].

The new release has been uploaded to addons.thunderbird.net and is waiting for the moderators there to approve it. If you would rather not wait for them, you can get it as follows:

* Download [this file][xpi] and save it to your local computer. If you're reading this in Firefox, make sure to right-click on the link and select "Save Link As..." rather than just clicking on it, or Firefox will try to install it as a Firefox add-on.
* Open the Add-ons page in Thunderbird (Tools > Add-ons and Themes).
* Click the gear icon at the top.
* Select "Install Add-on from File...".
* Browse to the file you saved and select it.
* Click through the dialogs to confirm installation.
* You can delete the downloaded file once you've installed it.

If you don't want to do this you can wait until the moderators approve it, though I can't say whether that will take hours or days.

I'm sorry about these bugs and I thank you for your patience as I've fixed them as rapidly as I could.

[rp]: https://github.com/Extended-Thunder/send-later/releases/tag/v10.1.1
[xpi]: https://github.com/Extended-Thunder/send-later/releases/download/v10.1.1/send_later.xpi

**Comment by Bluestone357** [comment]
Thanks ever so much - cheers.

**Comment by azuredusk10** [comment]
Thank you so much! I love the plug-in and am so grateful for your work
