### ISSUE TITLE
Not sending

### ISSUE THREAD

**Issue by vmtitov00** [Extended-Thunder/send-later#609]
Hi, after fixing the encription issue the extension saves the drafts but never moves them to outbox nor sends. Restarting TB (last build of v.102) and window$ does not help.

**Comment by nikkisiz23** [comment]
Having the same issue.

**Comment by Rings4** [comment]
Same. This is why I hate updating things. Addon is just completely broken now. I'm going to figure out how to roll back and permanently disable automatic updates.

**Comment by msjohns1** [comment]
Same. Installed the extension yesterday, tested, worked through the draft encryption issue, and everything worked. Today, after update, doesn't work at all. Messages sit in drafts and are never sent. Had a co-worker who also set up the extension on Friday, and it worked over the weekend, until today.

**Comment by jikamens** [comment]
I apologize for the inconvenience. There is indeed a bug I didn't catch before release that is impacting Thunderbird 102. I have a fix which I'll be releasing later today.

**Comment by jikamens** [comment]
I have released version 10.1.1 of Send Later which fixes all of the issues people have encountered today. The full list of fixes in this version is viewable on its [GitHub release page][rp].

The new release has been uploaded to addons.thunderbird.net and is waiting for the moderators there to approve it. If you would rather not wait for them, you can get it as follows:

* Download [this file][xpi] and save it to your local computer. If you're reading this in Firefox, make sure to right-click on the link and select "Save Link As..." rather than just clicking on it, or Firefox will try to install it as a Firefox add-on.
* Open the Add-ons page in Thunderbird (Tools > Add-ons and Themes).
* Click the gear icon at the top.
* Select "Install Add-on from File...".
* Browse to the file you saved and select it.
* Click through the dialogs to confirm installation.
* You can delete the downloaded file once you've installed it.

If you don't want to do this you can wait until the moderators approve it, though I can't say whether that will take hours or days.

I'm sorry about these bugs and I thank you for your patience as I've fixed them as rapidly as I could.

[rp]: https://github.com/Extended-Thunder/send-later/releases/tag/v10.1.1
[xpi]: https://github.com/Extended-Thunder/send-later/releases/download/v10.1.1/send_later.xpi

**Comment by vmtitov00** [comment]
Incredibly fast. Works now, many thanks

**Comment by Rings4** [comment]
Thank you for addressing this so quickly. Does this still require you to disable encrypted drafts? That didn't need to be done before, and I've re-enabled it since going back to 10.0.2.

**Comment by jikamens** [comment]
In 10.1.1: You still can't use encrypted drafts regardless of whether you're using PGP or S/MIME.

In 10.1.2: You will be able to use encrypted drafts with S/MIME but not PGP.

Note that if you were using encrypted drafts with PGP then that shouldn't have been working properly even before 10.1.0, and by "shouldn't have been working properly" I mean "Send Later would have encrypted your drafts with your own private key and then sent them to the recipient that way and the recipient would have been unable to read them."
