### ISSUE TITLE
remove all anonymous data collection from Send Later extension

### ISSUE THREAD

**Issue by axb21** [Extended-Thunder/send-later#611]
Anonymous data collection in a plugin that has full access to Thunderbird state is a dark pattern and should be removed. Please stop taking on the bad habits of trillion-dollar surveillance capitalists. The vast number of data breaches, data leaks, and ransomware attacks we see on a daily basis should give anyone pause before sharing data with a third party--even one with deep pockets and a dedicated information security staff. This extension should not be adopting these dangerous data collection practices.

I removed the Send Later extension because of this change in the latest release, and I will not even consider re-installing it until all telemetry and other data collection, no matter whether it's opt-in or opt-out, is removed.

**Comment by jikamens** [comment]
I believe it is possible to do this openly, transparently, honestly, securely, and with integrity, and I believe that's how I'm doing it. It is 100% possible for anyone, including you, to verify that I am telling the truth about everything that I am doing. The source code is open and easy to read, you can unpack the releases from addons.thunderbird.net to confirm that they match the source code, and if you want you can even build the extension from source and deploy it that way.  Heck, if you do that you can strip out the telemetry code and deploy a version without it, though honestly I don't know why you'd bother, since if you say no to the data collection that code is completely inoperational. :shrug:

There's even a link in my privacy policy showing the search you can do on the GitHub repository to identify every piece of data that's being collected by the telemetry.

In just a few hours of having the telemetry enabled I've already obtained definitive information that a change I was encouraged to make by a Thunderbird developer would actually break the add-on, something it would have been impossible for me to learn any other way. See #553.

Regarding the "full access" question, the only reason Send Later has such access is because it can't do what it needs to do without it because of deficiencies in the add-on APIs. I am working on eliminating those gaps—indeed, the goal of the issue referenced in the last paragraph is to eliminate one of them!—but in the meantime, every release of Send Later is reviewed by the moderators of addons.thunderbird.net (ATN) to confirm that I am not doing anything malicious, or accessing or transmitting any data I'm not supposed to. That will be true even when I've eliminated the need for the full access permission, because ATN's policy is to manually review all add-ons which have access to messages or contacts.

Given all this, I hope you will reconsider your decision not to use the add-on, but I'm not going to get rid of something which in my opinion is not violating anyone's privacy and has already proven to be beneficial to my users.
