### ISSUE TITLE
Send later sees all of my Thunderbird messages as "encrypted" and refuses to function. 

### ISSUE THREAD

**Issue by eaglew503** [Extended-Thunder/send-later#622]
This problem started last night.  It is not limited to just one of my computers but to others that I have Thunderbird installed as my email client.  I am hoping someone can fix this problem, so that I can take advantage of the send later add on.

**Comment by jikamens** [comment]
This issue should be fixed in release 10.1.3 of Send Later.

This release is available on addons.thunderbird.net, and unless you've turned off automatic add-on updates, Thunderbird will eventually update to the new version automatically. To update immediately:

* Go to [addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/versions/) and confirm that release 10.1.3 is available for download there.
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Send later.
* Click the gear icon and select "Check for Updates".
* The add-on should update and then you should see the message, "Your add-ons have been updated," next to the gear icon.

Please let me know if you still see this issue in this release.
