### ISSUE TITLE
Scheduling messages with Mail Merge not working in TB102

### ISSUE THREAD

**Issue by misaki-web** [Extended-Thunder/send-later#627]
On Send Later's documentation about [scheduling messages with Mail Merge](https://extended-thunder.github.io/send-later/#mail-merge-add-on), it says:

> Mail Merge has a "Date" field in the Mail Merge Dialog as part of the "Mail" section, which is visible if the user selects "Save As Draft" as "Deliver Mode" and Send Later is installed and activated. If you put a valid date in the "Date" field, then Mail Merge will tell Send Later to deliver the message at the specified date, just as if you scheduled it with Send Later directly. The "Date" field also supports variables! So it is possible to use a column "Date" (or "Time" or whatever you like to name it) with different dates for each recipient in the CSV. (Or if you want to use the Address Book, you probably will want to use Custom1 to Custom4 for this purpose.) In the "Date" field of the Mail Merge Dialog, you usually want to use something like this:
> 
> {{Date}} {{Time}}
> (There are probably other use cases with different variables as well.)

However, I'm not sure if it's a bug with Send Later or Mail Merge, but using Send Later v10.1.3, Mail Merge v9.6.1 and Thunderbird v102.13.0, it doesn't work.

In Mail Merge, I choose to save drafts. I click the "At" checkbox and fill either a date directly (like "2023-09-03 10:15") or variables (like "{{Date}} {{Time}}", with related columns in the CSV file), then I apply settings. Emails are saved as drafts, but the Send Later column stays empty, so emails are not sent later.

**Comment by jikamens** [comment]
You're right, this is broken! Thank you for reporting the issue.

Fixing it will require both a change to Send Later and a change to Mail Merge. I've implemented the change to Send Later and I'll hopefully be releasing it tonight. I've sent the necessary change to the maintainer of Mail Merge, but I can't say when he will release it.

**Comment by jikamens** [comment]
This issue (or, at least, the Send Later half of it) should be fixed in release 10.1.5 of Send Later. To check what version of Send Later you have:

* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Extensions on the left if you're not already on the left if you're not already there.
* Find Send Later in the list of extensions and click on it to open its details page.
* The version number should be displayed there next to
"Version".

This release is not yet available for download from addons.thunderbird.net, but you can download and install it from its [GitHub release page](https://github.com/Extended-Thunder/send-later/releases/tag/v10.1.5) as follows:

* Download [this file](https://github.com/Extended-Thunder/send-later/releases/download/v10.1.5/send_later.xpi) to your computer. (If you are using Firefox, make sure to right click on the link and select
"Save Link As..." rather than just clicking on it, because otherwise Firefox will try to install it as a Firefox add-on.)
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click the gear icon at the top and select "Install Add-on From File...".
* Browse to and select the downloaded file.
* Click through the installation pop-ups.
* You can delete the downloaded file once you've installed it into Thunderbird.

If you prefer to wait, the release will eventually be available on addons.thunderbird.net, and unless you've turned off automatic add-on updates, Thunderbird will eventually update to the new version automatically. To update immediately once it's available:

* Go to [addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/versions/) and confirm that release 10.1.5 is available for download there.
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Send later.
* Click the gear icon and select "Check for Updates".
* The add-on should update and then you should see the message, "Your add-ons have been updated," next to the gear icon.

Please let me know if you still see this issue in this release.

**Comment by jikamens** [comment]
I've implemented a full fix which should work with the current version of Mail Merge. This fix is available in release 10.1.6 of Send Later. To check what version of Send Later you have:

* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Extensions on the left if you're not already on the left if you're not already there.
* Find Send Later in the list of extensions and click on it to open its details page.
* The version number should be displayed there next to
"Version".

This release is not yet available for download from addons.thunderbird.net, but you can download and install it from its [GitHub release page](https://github.com/Extended-Thunder/send-later/releases/tag/v10.1.6) as follows:

* Download [this file](https://github.com/Extended-Thunder/send-later/releases/download/v10.1.6/send_later.xpi) to your computer. (If you are using Firefox, make sure to right click on the link and select
"Save Link As..." rather than just clicking on it, because otherwise Firefox will try to install it as a Firefox add-on.)
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click the gear icon at the top and select "Install Add-on From File...".
* Browse to and select the downloaded file.
* Click through the installation pop-ups.
* You can delete the downloaded file once you've installed it into Thunderbird.

If you prefer to wait, the release will eventually be available on addons.thunderbird.net, and unless you've turned off automatic add-on updates, Thunderbird will eventually update to the new version automatically. To update immediately once it's available:

* Go to [addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/versions/) and confirm that release 10.1.6 is available for download there.
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Send later.
* Click the gear icon and select "Check for Updates".
* The add-on should update and then you should see the message, "Your add-ons have been updated," next to the gear icon.

Please let me know if you still see this issue in this release.

**Comment by misaki-web** [comment]
@jikamens I've tested Send Later v10.1.6 and I confirm that the bug with Mail Merge is fixed. Thanks a lot for this very quick bug fix and for this very useful Thunderbird addon.
