### ISSUE TITLE
error messagebox but email is delivered 

### ISSUE THREAD

**Issue by corwinou** [Extended-Thunder/send-later#633]
### Prerequisites

- [X] I am reporting a problem, not asking a question (for questions, go to [Discussions](https://github.com/Extended-Thunder/send-later/discussions).
- [X] I have consulted the [user guide](https://extended-thunder.github.io/send-later/).
- [X] I have confirmed that I'm running the current version and the problem persists there (note the version number in fine print next to the add-on name [on addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/) and compare it to the version number listed in the add-on details opened from the Add-ons page in Thunderbird; if you've got an old version, click the gear icon and select "Check for Updates").
- [X] If I'm having an issue with date-parsing confusion, I've read the [section about that in the user guide](https://extended-thunder.github.io/send-later/#date-format-confusion-in-the-scheduler-pop-up) and I still think this is something different.
- [X] If I'm having an issue with messages not being delivered, I've followed the [troubleshooting steps in the user guide](https://extended-thunder.github.io/send-later/#messages-dont-send-or-send-multiple-times) and it's still an issue.

### Describe the bug

A scheduled message is sent at the correct timeframe, but with an error message just pops up: (UI localized in french)
Messagebox title: Erreur d'envoi du message
L’envoi du message a échoué.
Une erreur est survenue lors de l’envoi de l’e-mail : erreur du serveur SMTP. Le serveur a répondu : Service not available, closing transmission channel.
A bit annoying... Any idea how to avoid this?

### How to reproduce

Systematic. Tried to remove and reinstall SendLater, same behavior

### Expected behavior

With TB <115 it was working fine.

### Operating System

Windows

### Operating System Version

11

### Thunderbird version

115.2

**Comment by jikamens** [comment]
Thank you for reporting issue.

I can troubleshoot this with you if you'd like, but the executive summary is that by the time you get this error, things are out of Send Later's hands, so it's likely that I won't be able to do anything about it.

The way Send Later delivers messages is by copying them into your Outbox (underneath Local Folders) and then telling Thunderbird itself to deliver any messages currently in the Outbox. At that point delivery is handled entirely by Thunderbird and Send Later has no control over it.

To troubleshoot this we would need to enable IMAP logging so we can see exactly what the server is telling Thunderbird when it attempts to deliver the message.

There is one quick test we can do which may be helpful:

1. Disable the Send Later add-on on the Add-ons page.
2. Compose a new message.
3. After entering a recipient and subject, select the File > Send Later menu command.
4. Because Send Later is disabled, this should put the message in your Outbox.
5. In the main Thunderbird window, select the File > Send Unsent Messages command. This should cause the message in your Outbox to be delivered.

When you do this test do you get the same error pop-up?

Does the error pop-up occur when you are actively using Thunderbird at message delivery time, or only when a message's delivery time arrives when you are away from your computer?

Just to confirm this happens every time Send Later delivers a message?

Do you ever get this same error when you send messages normally?

**Comment by corwinou** [comment]
Hi,
Thank you for your reply. 
Strange issue as I never get this error with TB<115 during direct delivery or using SendLater for years

I followed the steps of your quick test, and yes I got the same error message, but about 30-40 seconds later... 
So I will try to understand what has changed on TB side and check IMAP communication.
