### ISSUE TITLE
Ability to remove in XX minutes buttons from dialog?

### ISSUE THREAD

**Issue by david-macias** [Extended-Thunder/send-later#639]
**Describe the solution you'd like**
I like to always specify when I want the email to be sent out. So I have no need for the "send in 15 minutes" button or the others. Because how many send buttons are presented and so close together I always have to think twice before I confirm the right send later button.

**Describe alternatives you've considered**
I would love if these buttons could be toggled off as part of the settings tab, so this becomes a user preference and not a default.

**Comment by jikamens** [comment]
A reasonable idea. Should be able to hide the buttons in the pop-up if their settings are empty in the preferences. Thanks for the suggestion!

**Comment by jikamens** [comment]
This issue should be fixed in release 10.2.5 of Send Later.

To check what version of Send Later you have:

* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Extensions on the left if you're not already on the left if you're not already there.
* Find Send Later in the list of extensions and click on it to open its details page.
* The version number should be displayed there next to
"Version".

This release is not yet available for download from addons.thunderbird.net, but you can download and install it from its [GitHub release page](https://github.com/Extended-Thunder/send-later/releases/tag/v10.2.5) as follows:

* Download [send_later.xpi](https://github.com/Extended-Thunder/send-later/releases/download/v10.2.5/send_later.xpi) to your computer. (If you are using Firefox, make sure to right click on the link and select
"Save Link As..." rather than just clicking on it, because otherwise Firefox will try to install it as a Firefox add-on.)
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click the gear icon at the top and select "Install Add-on From File...".
* Browse to and select the downloaded file.
* Click through the installation pop-ups.
* You can delete the downloaded file once you've installed it into Thunderbird.

To subscribe to future beta releases (we love beta testers!), download and install [send_later_beta.xpi](https://github.com/Extended-Thunder/send-later/releases/download/v10.2.5/send_later_beta.xpi) instead. The advantage is that if there's a bug that affects your workflow you'll help find it and get it fixed quickly. The disadvantage is that bugs are a bit more likely in beta releases. You can unsubscribe from beta releases at any time by downloading and installing send_later.xpi or installing from [addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/).

Note that this is a prerelease. While we make every effort to ensure that prereleases are stable, they are a bit more likely to have bugs, so proceed with caution.

If you prefer to wait, the release will eventually be available on addons.thunderbird.net, and unless you've turned off automatic add-on updates, Thunderbird will eventually update to the new version automatically. To update immediately once it's available:

* Go to [addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/versions/) and confirm that release 10.2.5 is available for download there.
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Send later.
* Click the gear icon and select "Check for Updates".
* The add-on should update and then you should see the message, "Your add-ons have been updated," next to the gear icon.

Please let me know if you still see this issue in this release.

**Comment by jikamens** [comment]
The info will be in the user guide once this version of the add-on ships to everyone.

There are some features that are sufficiently esoteric that it's OK for people to have to go read the user guide to figure them out. This one falls into that category. ;-)

**Comment by david-macias** [comment]
Ha ha, I don't agree with it, but I respect the stance. Thanks again for the awesome work!
