### ISSUE TITLE
Send Later fails to send messages and they completely disappear

### ISSUE THREAD

**Issue by paulgir** [Extended-Thunder/send-later#644]
### Prerequisites

- [X] I am reporting a problem, not asking a question (for questions, go to [Discussions](https://github.com/Extended-Thunder/send-later/discussions).
- [X] I have consulted the [user guide](https://extended-thunder.github.io/send-later/).
- [X] I have confirmed that I'm running the current version and the problem persists there (note the version number in fine print next to the add-on name [on addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/) and compare it to the version number listed in the add-on details opened from the Add-ons page in Thunderbird; if you've got an old version, click the gear icon and select "Check for Updates").
- [X] If I'm having an issue with date-parsing confusion, I've read the [section about that in the user guide](https://extended-thunder.github.io/send-later/#date-format-confusion-in-the-scheduler-pop-up) and I still think this is something different.
- [X] If I'm having an issue with messages not being delivered, I've followed the [troubleshooting steps in the user guide](https://extended-thunder.github.io/send-later/#messages-dont-send-or-send-multiple-times) and it's still an issue.

### Describe the bug

Send Later shows the message is waiting to be sent from the Drafts folder.
After the set 5 minute sending delay the message disappears  from the Drafts folder but does not appear in the Sent folder.
If Thunderbird is closed and reopened a warning message saying "Do you want to send unsent messages now" appears but clicking on "yes" does nothing.  If Thunderbird is closed and reopened again the warning message reappears.
The email message is lost and cannot be retrieved.

### Expected behavior

Send Later shows the message is waiting to be sent from the Drafts folder.
After the set 5 minute sending delay the message disappears  from the Drafts folder and appears in the Sent folder.

### Operating System

Ubuntu

### Operating System Version

23.04

### Thunderbird version

115 Snap

### Send Later start-up string

Send Later version 10.1.9 on Thunderbird 115.2.2 (20230912052425) [linux x86-64] UI locale en-US, Date Locale en-NZ

**Comment by paulgir** [comment]
Hi
Thanks for the prompt reply.
I only have "Sent" folders no "Outbox" exists in the folder tree  - I checked after reading the user guide .
I don't know if that is a difference between Windows Thunderbird and Linux Thunderbird or because I use Unified folders .
The former behaviour of Send later was as I described:
When the Send button was pressed the message would appear in the Drafts folder and after the allotted delay (5 minutes) the message would be sent and the message would appear in the Sent folder.
I have been using Send Later for some time - formerly using the Thunderbird ESR PPA and now using the Thunderbird 115 Snap package and the behaviour was always as above.
Send Later was working well up to 2 days ago in the Thunderbird 115 Snap package.
At the moment I have disabled Send Later

**Comment by jikamens** [comment]
You have an Outbox folder.

It's under Local Folders, as I said.

If you can't find it, I can't help you further.

Once you've found it, do the [troubleshooting steps](https://extended-thunder.github.io/send-later/#messages-dont-send-or-send-multiple-times) that I have now referred you to three times. Take notes while you're doing the troubleshooting steps of the results at each step so you can post them here.

If you're still having trouble after doing the troubleshooting steps, then post your notes here about the troubleshooting steps you did and what the result was.

If you can't do that, I can't help you further.

There are some bug fixes in the upcoming release that _may_ be relevant to the problem you're having, though I can't say for certain since you haven't done any of the troubleshooting steps. If you'd like, though, you can try the prerelease version of the next release to see if it helps. This release is not yet available for download from addons.thunderbird.net, but you can download and install it from its [GitHub release page](https://github.com/Extended-Thunder/send-later/releases/tag/v10.2.8) as follows:

* Download [send_later.xpi](https://github.com/Extended-Thunder/send-later/releases/download/v10.2.8/send_later.xpi) to your computer. (If you are using Firefox, make sure to right click on the link and select
"Save Link As..." rather than just clicking on it, because otherwise Firefox will try to install it as a Firefox add-on.)
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click the gear icon at the top and select "Install Add-on From File...".
* Browse to and select the downloaded file.
* Click through the installation pop-ups.
* You can delete the downloaded file once you've installed it into Thunderbird.

To subscribe to future beta releases (we love beta testers!), download and install [send_later_beta.xpi](https://github.com/Extended-Thunder/send-later/releases/download/v10.2.8/send_later_beta.xpi) instead. The advantage is that if there's a bug that affects your workflow you'll help find it and get it fixed quickly. The disadvantage is that bugs are a bit more likely in beta releases. You can unsubscribe from beta releases at any time by downloading and installing send_later.xpi or installing from [addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/).

Note that this is a prerelease. While we make every effort to ensure that prereleases are stable, they are a bit more likely to have bugs, so proceed with caution.

**Comment by paulgir** [comment]
Afraid not
Searches for "outbox" in the following directories:
/home/<user>/snap/thunderbird
/home/<user>/.thunderbird
/snap/thunderbird
result in no results
Sreenshot of the folder pane:
![Screenshot from 2023-09-15 15-05-56](https://github.com/Extended-Thunder/send-later/assets/63628392/51801836-4930-48da-9d59-153030d06c17)

**Comment by paulgir** [comment]
Ok . Local Folders is sitting in Trash , for some reason.
There are no options to move it elsewhere and I can't expand it.
It seems the directory tree is messed up.

**Comment by jikamens** [comment]
I don't know how you deleted Local Folders or how to restore it, but I can tell you you're not supposed to do that or even supposed to be able to do that and that's almost certainly why Send Later isn't working.

The only fix I can suggest is for you to [delete and recreate your Thunderbird profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-thunderbird-profiles). Perhaps the folks over at the [Thunderbird support form](https://support.mozilla.org/products/thunderbird) will be able to suggest a less drastic solution, but I don't know of one.

Closing this ticket because this is not a Send Later issue.
