### ISSUE TITLE
[Dev]: Strange issue catching rejected Promises with .catch().

### ISSUE THREAD

**Issue by jobisoft** [Extended-Thunder/send-later#647]
### Describe the bug

This is not a bug, it is a concept we use which I found out today may have issues. I stumbled upon this during review of core code:
https://phabricator.services.mozilla.com/D188734#6258613

It basically means, that constructs like this:

```
let rv = await something().catch(err => {
 // do something with err
 });
```
 
 do not always work. I have not understood why. @arndissler: Any idea ? There is reproducer code in the linked phabricator comment.
 
 We use this concept quite often.

**Comment by RealRaven2000** [comment]
Hmm, looks like I used the pattern in the code where I handle a message from Cardbook - pretty sure this code may actually be from Phillipe originally, so he may have used it elsewhere, too.

**Comment by jikamens** [comment]
On the extension side of things, the async API are not actually JavaScript async. They're actually synchronous functions that return a promise:

![image](https://github.com/Extended-Thunder/send-later/assets/1598067/815fe0ab-9a39-4640-a095-5acd5332bd64)

They do things like argument checking synchronously, before they construct and return the `Promise`. If the things they do synchronously fail, that's not going to be caught by `.catch()`.

The fix is to make them real async functions and instead of returning the Promise they create they should await for it.

I.e., this appears to be a structural bug with how these API functions are implemented.

Look at toolkit/components/extensions/Schemas.sys.mjs in gecko, specifically, FunctionEntry.getDescriptor.

Fixing the structural bug will require buy-in from the Firefox team and I am certainly not nearly enough of a JavaScript wizard to know how it would be done, though I assume it is possible to do it.

**Comment by jikamens** [comment]
I'm not sure why you opened this issue in the Send Later project. Is there code in Send Later which you think may be passing incorrect argument types to API functions and therefore is vulnerable to this issue?

**Comment by jobisoft** [comment]
> I'm not sure why you opened this issue in the Send Later project. Is there code in Send Later which you think may be passing incorrect argument types to API functions and therefore is vulnerable to this issue?

In the last weeks we have tried to reduce glitches in SendLater and while doing so we considered the concept of

`await something().catch()`

to be a good idea. We use it a lot (a simple search will show that).

At the moment of filing the issue, I only had this one reproduce case which happens to be due to invalid parameters. In a matrix discussion with @arndissler yesterday, we came to the same conclusion as you, that it happens when a function returns an explicit Promise instead of being an async function. I have not checked the code for that, yet, bu it is still a possible glitch cause.

I created the issue to raise awareness. You are of course free to close it.

**Comment by jikamens** [comment]
Fair enough. I don't use `.catch()` all that much in the code, but I went through and reviewed the ones I use and updated some of them to use `try/catch` instead. From that review I doubt that this was a significant issue in Send Later but it doesn't hurt to make the code a bit more robust.

**Comment by jikamens** [comment]
Thanks for the heads-up.
