### ISSUE TITLE
BCC addresses are not updated when a saved draft is edited and saved

### ISSUE THREAD

**Issue by nylimited** [Extended-Thunder/send-later#666]
### Prerequisites

- [X] I am reporting a problem, not asking a question (for questions, go to [Discussions](https://github.com/Extended-Thunder/send-later/discussions)).
- [X] I have consulted the [user guide](https://extended-thunder.github.io/send-later/).
- [X] I have confirmed that I'm running the current version and the problem persists there (note the version number in fine print next to the add-on name [on addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/) and compare it to the version number listed in the add-on details opened from the Add-ons page in Thunderbird; if you've got an old version, click the gear icon and select "Check for Updates").
- [X] If I'm having an issue with date-parsing confusion, I've read the [section about that in the user guide](https://extended-thunder.github.io/send-later/#date-format-confusion-in-the-scheduler-pop-up) and I still think this is something different.
- [X] If I'm having an issue with messages not being delivered, I've followed the [troubleshooting steps in the user guide](https://extended-thunder.github.io/send-later/#messages-dont-send-or-send-multiple-times) and it's still an issue.

### Describe the bug

Editing a saved draft with, say, 20 email addresses on the BCC line, replacing them all with 22 addresses.  Saving the draft will retain the original 20 addresses only.

### How to reproduce

My contacts are on Google and I am using the CardBook Thunderbird add-on in Linux. 
On Google I use "Labels" to have people grouped.

When I create an email I often use a label name in the BCC field which is expanded by Thunderbird with each email address.

For this example, let's say there are 20 addresses specified by the label..
Let's say I now set this email to send later, on January 1st.

Some time later I realise I had to add 2 more people to the Gmail label. 
I update the Google contacts, I re-sync CardBook.
I edit the draft email in TB and delete all 20 addresses from the BCC line.
Once again, I type the label name and Thunderbird fills in the email addresses.
Yes, there are now 22 addresses on the BCC line, as expected. The label correctly included the 2 additions.

I once again save the draft with Send Later to be sent on the same date/time (January 1) as before by clicking on the date/time shown by the save process.

I look at the BCC line of the newly saved draft and I see only the original 20 addresses. 
The 2 new ones were dropped during the save somehow. 
Or, more likely, the BCC line was not replaced with the new one before saving.

I can repeat this process on any previously saved draft or the same draft, over and over with the same result.
I suspect using the label process and Cardbook may have nothing to do with the issue but included for completeness.

### Expected behavior

I expected the process to include the 2 new additions in the above example, completely replacing the BCC info after the edit.

### Additional context

I think that when I edit the already saved draft and exit the process (thus removing the Save Later info) I create a new, clean draft. If I now replace the BCC addresses and save with Send Later the correct info will be saved - possibly because the old BCC info is no longer present.

### Operating System

Linux Mint

### Operating System Version

21.2 (Victoria)

### Thunderbird version

115.4.3

### Send Later start-up string

Disabled/enabled add-on.  
Nothing showed up.

**Comment by nylimited** [comment]
Here is a bit more info that might be helpful ...

1. The BCC data is not the only thing that will not update correctly. I also tried to make an independent change to occurrence (send every x years) it too was not saved after the edit.

2. The way to get around the issue is to edit twice, regardless of the problematic change. Simply open the draft on the Thunderbird editor and, without making any changes, click the "x" on the top right of the window and force close it. No changes were made hence nothing should have changed BUT ...   re-open the draft immediately again, make the change and click Send Later, change the occurrence if desired and save.  All data will now be updated.

Somehow, clicking the X to force close window drops all the Send Later info (which may make sense since TB does not know about it) and forces Send Later to start clean, remembering nothing. A pain the rear to do it if you have a lot of drafts to update but seems to work well.

**Comment by jikamens** [comment]
This issue should be fixed in release 10.3.4 of Send Later.

To check what version of Send Later you have:

* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Extensions on the left if you're not already on the left if you're not already there.
* Find Send Later in the list of extensions and click on it to open its details page.
* The version number should be displayed there next to
"Version".

This release is not yet available for download from addons.thunderbird.net, but you can download and install it from its [GitHub release page](https://github.com/Extended-Thunder/send-later/releases/tag/v10.3.4) as follows:

* Download [send_later_10.3.4.xpi](https://github.com/Extended-Thunder/send-later/releases/download/v10.3.4/send_later_10.3.4.xpi) to your computer.
(If you are using Firefox, make sure to right click on the link and select "Save Link As..." rather than just clicking on it, because otherwise Firefox will try to install it as a Firefox add-on.)
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click the gear icon at the top and select "Install Add-on From File...".
* Browse to and select the downloaded file.
* Click through the installation pop-ups.
* You can delete the downloaded file once you've installed it into Thunderbird.

To subscribe to future beta releases (we love beta testers!), download and install [send_later_beta_10.3.4.xpi](https://github.com/Extended-Thunder/send-later/releases/download/v10.3.4/send_later_10.3.4_beta.xpi) instead. The advantage is that if there's a bug that affects your workflow you'll help find it and get it fixed quickly. The disadvantage is that bugs are a bit more likely in beta releases. You can unsubscribe from beta releases at any time by downloading and installing send_later.xpi or installing from [addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/).

Note that this is a prerelease. While we make every effort to ensure that prereleases are stable, they are a bit more likely to have bugs, so proceed with caution.

If you prefer to wait, the release will eventually be available on addons.thunderbird.net, and unless you've turned off automatic add-on updates, Thunderbird will eventually update to the new version automatically. To update immediately once it's available:

* Go to [addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/versions/) and confirm that release 10.3.4 is available for download there.
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Send later.
* Click the gear icon and select "Check for Updates".
* The add-on should update and then you should see the message, "Your add-ons have been updated," next to the gear icon.

Please let me know if you still see this issue in this release.
