### ISSUE TITLE
Send message error but message is sent

### ISSUE THREAD

**Issue by roorco** [Extended-Thunder/send-later#674]
### Prerequisites

- [X] I am reporting a problem, not asking a question (for questions, go to [Discussions](https://github.com/Extended-Thunder/send-later/discussions)).
- [X] I have consulted the [user guide](https://extended-thunder.github.io/send-later/).
- [X] I have confirmed that I'm running the current version and the problem persists there (note the version number in fine print next to the add-on name [on addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/) and compare it to the version number listed in the add-on details opened from the Add-ons page in Thunderbird; if you've got an old version, click the gear icon and select "Check for Updates").
- [X] If I'm having an issue with date-parsing confusion, I've read the [section about that in the user guide](https://extended-thunder.github.io/send-later/#date-format-confusion-in-the-scheduler-pop-up) and I still think this is something different.
- [X] If I'm having an issue with messages not being delivered, I've followed the [troubleshooting steps in the user guide](https://extended-thunder.github.io/send-later/#messages-dont-send-or-send-multiple-times) and it's still an issue.

### Describe the bug

Hi,
I'm having this error only when Send later plug-in is active.
```
Sending of the message failed.
An error occurred when sending mail: Outgoing server (SMTP error. The server responded: mysite.com Service closing transmission channel. )
```
The message is sent but I've got an message of error.
Sometimes the message doesn't appear.
I have two accounts, one on gmail (with no copy of sent email), the other on a french server (with copy of sent email).
I'm testing to have no copy at all of sent messages on both account and the error persists.

### Operating System

Windows 11

### Thunderbird version

115 Betterbird, but in Thunderbird I had the same problem

**Comment by roorco** [comment]
I'm not sure anymore the reason of the message, but it seems gone for the moment and I can't reproduce it. I'm closing the issue.

**Comment by jikamens** [comment]
This is a Thunderbird bug, not a Send Later bug. You can report it at https://bugzilla.mozilla.org/ if you would like.

**Comment by jikamens** [comment]
As a workaround, you can go into the Thunderbird [advanced configuration editor](https://support.mozilla.org/en-US/kb/config-editor) and add a number preference `mail.smtpserver.smtp#.max_messages_per_connection`, where `#` is the number of the server that is having this problem (I'll explain in a minute how to determine that), with the value `1`. This should prevent Thunderbird from trying to reuse SMTP connections, so this problem will hopefully go away.

To figure out the correct number to use in the preference, search for `mail.smtpserver` in the advanced configuration editor and find the one whose `hostname` is the name of the server that's having the problem.

If you'd like to just enable that setting for all SMTP servers you can add a number preference `mail.smtpserver.default.max_messages_per_connection` instead of worrying about which specific server to set it for.

Changing this setting may cause a minor performance impact (delay) when sending messages.
