### ISSUE TITLE
Thunderbird tries to connect to server although account is disabled

### ISSUE THREAD

**Issue by 1u** [Extended-Thunder/send-later#676]
### Prerequisites

- [X] I am reporting a problem, not asking a question (for questions, go to [Discussions](https://github.com/Extended-Thunder/send-later/discussions)).
- [X] I have consulted the [user guide](https://extended-thunder.github.io/send-later/).
- [X] I have confirmed that I'm running the current version and the problem persists there (note the version number in fine print next to the add-on name [on addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/) and compare it to the version number listed in the add-on details opened from the Add-ons page in Thunderbird; if you've got an old version, click the gear icon and select "Check for Updates").
- [X] If I'm having an issue with date-parsing confusion, I've read the [section about that in the user guide](https://extended-thunder.github.io/send-later/#date-format-confusion-in-the-scheduler-pop-up) and I still think this is something different.
- [X] If I'm having an issue with messages not being delivered, I've followed the [troubleshooting steps in the user guide](https://extended-thunder.github.io/send-later/#messages-dont-send-or-send-multiple-times) and it's still an issue.

### Describe the bug

at least 3 new "Send Later" related Bugs in one week, see here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1874109
https://bugzilla.mozilla.org/show_bug.cgi?id=1874134
https://bugzilla.mozilla.org/show_bug.cgi?id=1874845

People having one mail account disabled or no password stored, find Thunderbird still trying to connect to that server while Send Later extension is enabled.

That was not the case on my side for long time before updating Thunderbird.

### How to reproduce

e.g.
Configure an account NOT to download emails at startup & NOT to download emails every X minutes.
set accounts server host name to e.g. localhost.

-> notification popup every minute or so telling me that there was a timeout while attempting to connect to an account, that is "disabled"

### Expected behavior

No connection to this email server should be attempted => not timeout should occur => no popup should appear

### Operating System

Linux

### Thunderbird version

115.6.0

**Comment by liar666** [comment]
Same problem here.
See screenshot of configuration and error messages here: https://bugzilla.mozilla.org/show_bug.cgi?id=1874134

**Comment by guest4711** [comment]
Can confirm the problem.

**Comment by jikamens** [comment]
This issue should be fixed in release 10.3.6 of Send Later.

To check what version of Send Later you have:

* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Extensions on the left if you're not already on the left if you're not already there.
* Find Send Later in the list of extensions and click on it to open its details page.
* The version number should be displayed there next to
"Version".

This release is not yet available for download from addons.thunderbird.net, but you can download and install it from its [GitHub release page](https://github.com/Extended-Thunder/send-later/releases/tag/v10.3.6) as follows:

* Download [send_later_10.3.6.xpi](https://github.com/Extended-Thunder/send-later/releases/download/v10.3.6/send_later_10.3.6.xpi) to your computer.
(If you are using Firefox, make sure to right click on the link and select "Save Link As..." rather than just clicking on it, because otherwise Firefox will try to install it as a Firefox add-on.)
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click the gear icon at the top and select "Install Add-on From File...".
* Browse to and select the downloaded file.
* Click through the installation pop-ups.
* You can delete the downloaded file once you've installed it into Thunderbird.

To subscribe to future beta releases (we love beta testers!), download and install [send_later_beta_10.3.6.xpi](https://github.com/Extended-Thunder/send-later/releases/download/v10.3.6/send_later_10.3.6_beta.xpi) instead. The advantage is that if there's a bug that affects your workflow you'll help find it and get it fixed quickly. The disadvantage is that bugs are a bit more likely in beta releases. You can unsubscribe from beta releases at any time by downloading and installing send_later.xpi or installing from [addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/).

If you prefer to wait, the release will eventually be available on addons.thunderbird.net, and unless you've turned off automatic add-on updates, Thunderbird will eventually update to the new version automatically. To update immediately once it's available:

* Go to [addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/versions/) and confirm that release 10.3.6 is available for download there.
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Send later.
* Click the gear icon and select "Check for Updates".
* The add-on should update and then you should see the message, "Your add-ons have been updated," next to the gear icon.

Please let me know if you still see this issue in this release.

**Comment by guest4711** [comment]
Thank you. The new account selection is useful.
