### ISSUE TITLE
Clicking Send Later causes window ot de-maximalize.

### ISSUE THREAD

**Issue by MarekKnapek** [Extended-Thunder/send-later#685]
### Prerequisites

- [X] I am reporting a problem, not asking a question (for questions, go to [Discussions](https://github.com/Extended-Thunder/send-later/discussions)).
- [X] I have consulted the [user guide](https://extended-thunder.github.io/send-later/).
- [X] I have confirmed that I'm running the current version and the problem persists there (note the version number in fine print next to the add-on name [on addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/) and compare it to the version number listed in the add-on details opened from the Add-ons page in Thunderbird; if you've got an old version, click the gear icon and select "Check for Updates").
- [X] If I'm having an issue with date-parsing confusion, I've read the [section about that in the user guide](https://extended-thunder.github.io/send-later/#date-format-confusion-in-the-scheduler-pop-up) and I still think this is something different.
- [X] If I'm having an issue with messages not being delivered, I've followed the [troubleshooting steps in the user guide](https://extended-thunder.github.io/send-later/#messages-dont-send-or-send-multiple-times) and it's still an issue.

### Describe the bug

I new message window click the Send Later button, the window gets de-maximalized.

### How to reproduce

 - Open new message window.
 - Maximalize it.
 - Click the Send Later button.
 - The window gets de-maximalized, but its size is the same as-if it is maximalized.
 - If I decide to create new message later, the new message window size and position is screwed. It should stay the same as before pressing any Send Later button, but instead it is de-maximalized and big as the whole screen.

### Expected behavior

 - If the new message window is maximalized, it should stay maximalized after pressing the Send Later button.
 - Don't screw saved new message de-maximalized position and size.

### Additional context

Windows Server 2022 x64 with all updates, Thunderbird x64 with all updates, Send Later latest greatest version.

### Thunderbird version

115.8.0 (64-bit)

**Comment by jikamens** [comment]
This is nothing Send Later is doing. If Thunderbird thinks it's correct to de-maximize the window when it opens a pop-up attached to a browser action button, Send Later has no control over that. If you wish you can file a Thunderbird bug about this at https://bugzilla.mozilla.org/.
Note that for other reasons the next Send Later release will be changing the pop-up from one that is attached to the browser action button to a separate window, so that may make this problem go away temporarily, but once the Thunderbird bug necessitating that change is fixed it will go back to being attached to the browser action button since that is, overall, the preferred behavior, for various reasons.
