### ISSUE TITLE
Send later popup does not close after sending

### ISSUE THREAD

**Issue by Feri-6** [Extended-Thunder/send-later#689]
### Prerequisites

- [X] I am reporting a problem, not asking a question (for questions, go to [Discussions](https://github.com/Extended-Thunder/send-later/discussions)).
- [X] I have consulted the [user guide](https://extended-thunder.github.io/send-later/).
- [X] I have confirmed that I'm running the current version and the problem persists there (note the version number in fine print next to the add-on name [on addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/) and compare it to the version number listed in the add-on details opened from the Add-ons page in Thunderbird; if you've got an old version, click the gear icon and select "Check for Updates").
- [X] If I'm having an issue with date-parsing confusion, I've read the [section about that in the user guide](https://extended-thunder.github.io/send-later/#date-format-confusion-in-the-scheduler-pop-up) and I still think this is something different.
- [X] If I'm having an issue with messages not being delivered, I've followed the [troubleshooting steps in the user guide](https://extended-thunder.github.io/send-later/#messages-dont-send-or-send-multiple-times) and it's still an issue.

### Describe the bug

If I click on the Send Later button on the Message composition window, and I click on the "Send Now" button on the pop up window, the composition window closes but the pop up does not. I can close it with the X button.

Error on the console:
Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
[popup.js:149](moz-extension://45812e34-85e1-493f-89a5-c0b190a09905/ui/popup.js)
    doSendNow moz-extension://45812e34-85e1-493f-89a5-c0b190a09905/ui/popup.js:149

### How to reproduce

1. Click on the Send Later button on the message composition window.
2. Click on the "Send Now" button on the pop up window.
3. The composition window closes, but the pop up does not.

### Expected behavior

Pop up window closes.

### Operating System

Windows

### Operating System Version

11

### Thunderbird version

102.15.1

### Send Later start-up string

WebExtensions: Error setting Sugar locale to hu-HU: TypeError: Invalid Locale: hu-HU TypeError: Invalid Locale: hu-HU
    set jar:file:///C:/Users/Feri/AppData/Roaming/Thunderbird/Profiles/qs4bkyp2.default-release/extensions/sendlater3@kamens.us.xpi!/utils/sugar-custom.js:3714
    setLocale jar:file:///C:/Users/Feri/AppData/Roaming/Thunderbird/Profiles/qs4bkyp2.default-release/extensions/sendlater3@kamens.us.xpi!/utils/sugar-custom.js:4752
    <anonymous> jar:file:///C:/Users/Feri/AppData/Roaming/Thunderbird/Profiles/qs4bkyp2.default-release/extensions/sendlater3@kamens.us.xpi!/utils/static.js:2277
    getAPI jar:file:///C:/Users/Feri/AppData/Roaming/Thunderbird/Profiles/qs4bkyp2.default-release/extensions/sendlater3@kamens.us.xpi!/experiments/legacyColumnImplementation.js:321
    asyncLoadAPI resource://gre/modules/ExtensionCommon.jsm:1296

**Comment by jikamens** [comment]
1. That's not the Send Later start-up string. Please open the add-ons page and click on Send Later to find out which version you are using and paste the Send Later version number here.
2. This is almost certainly being caused by an incompatibility between Send Later and another add-on you have installed. What other add-ons are you using?

**Comment by dajiahao** [comment]
how to find out which addon causes this? I have the same effect like the thread-opener since some months now ... it's just an extra click to close the window, everything else works fine; right now I am on version 10.5.1 of sendlater on tb 115.13.0/linux

**Comment by jikamens** [comment]
>how to find out which addon causes this?

Disable the other add-ons one at a time, restart Thunderbird after disabling each one, test Send Later after each, see when the problem goes away.

**Comment by Feri-6** [comment]
I started this issue. I disabled all addons, but the Send later windows stays after sending.

**Comment by jikamens** [comment]
Do you happen to have a YubiKey plugged in? See #656.

**Comment by Feri-6** [comment]
Nope.
Enabled plugins:
![image](https://github.com/user-attachments/assets/54475a17-0d1e-41db-a71f-b748baa11543)

**Comment by jikamens** [comment]
Hmm. Can you follow the [instructions in the user guide](https://extended-thunder.github.io/send-later/#console-logging) for capturing logs in the error console when you click the Send button in the scheduling window and it doesn't close? I'm hoping there is a log message indicating what's going wrong.

**Comment by 121sim** [comment]
I'm experiencing the same bug (MacOS). I'm sending the error log by email.
Thanks.

**Comment by jikamens** [comment]
This issue should be fixed in release 10.5.4 of Send Later.

To check what version of Send Later you have:

* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Extensions on the left if you're not already on the left if you're not already there.
* Find Send Later in the list of extensions and click on it to open its details page.
* The version number should be displayed there next to
"Version".

This release is not yet available for download from addons.thunderbird.net, but you can download and install it from its [GitHub release page](https://github.com/Extended-Thunder/send-later/releases/tag/v10.5.4) as follows:

* Download [send_later_10.5.4.xpi](https://github.com/Extended-Thunder/send-later/releases/download/v10.5.4/send_later_10.5.4.xpi) to your computer.
(If you are using Firefox, make sure to right click on the link and select "Save Link As..." rather than just clicking on it, because otherwise Firefox will try to install it as a Firefox add-on.)
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click the gear icon at the top and select "Install Add-on From File...".
* Browse to and select the downloaded file.
* Click through the installation pop-ups.
* You can delete the downloaded file once you've installed it into Thunderbird.

To subscribe to future beta releases (we love beta testers!), download and install [send_later_beta_10.5.4.xpi](https://github.com/Extended-Thunder/send-later/releases/download/v10.5.4/send_later_10.5.4_beta.xpi) instead. The advantage is that if there's a bug that affects your workflow you'll help find it and get it fixed quickly. The disadvantage is that bugs are a bit more likely in beta releases. You can unsubscribe from beta releases at any time by downloading and installing send_later.xpi or installing from [addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/).

Note that this is a prerelease. While we make every effort to ensure that prereleases are stable, they are a bit more likely to have bugs, so proceed with caution.

If you prefer to wait, the release will eventually be available on addons.thunderbird.net, and unless you've turned off automatic add-on updates, Thunderbird will eventually update to the new version automatically. To update immediately once it's available:

* Go to [addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/versions/) and confirm that release 10.5.4 is available for download there.
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Send later.
* Click the gear icon and select "Check for Updates".
* The add-on should update and then you should see the message, "Your add-ons have been updated," next to the gear icon.

Please let me know if you still see this issue in this release.

**Comment by 121sim** [comment]
Thanks, fixed for me.
