### ISSUE TITLE
Feature request: would be able to use to it throttle send rates by seconds..

### ISSUE THREAD

**Issue by petrosmm** [Extended-Thunder/send-later#72]
I really like this add-on. Similar to Mail Merge, would be ideal to throttle send rates using the "pause" range.

**Comment by jperryhouts** [comment]
Am I understanding your suggestion correctly that Send Later do a single send operation at once, with a programmable delay after each one?

**Comment by petrosmm** [comment]
This is correct! I would say delays in the seconds, something no one ever does, but I think it's a fantastic idea.

**Comment by jperryhouts** [comment]
What do you propose the behavior should be if the process of sending all scheduled messages with delays takes a significant amount of time (in particular, if it takes longer than the "check every" preference)? I don't know what the expected behavior would be in that case. My intuition says it should send each message in sequence, then wait its usual timeout before its next loop, but that might be confusing in some cases if it isn't what the user expects.

**Comment by petrosmm** [comment]
As a mid-level between a junior and a senior/architect, I have learned that software engineers develop their software for either specific uses, the most common use cases, or both. This does not make my opinion dogma. I think with delays the point is to be hitting a minimum time waited, anytime a program freezes because the system halts/pauses a thread, it delays a process, as well even if there is no intention. As long as delays are satisfied minimally, it will help with the outcome. If you are curious about my use case, it's a form of throttling for sending e-mails so you do not hit limits etc.

**Comment by jperryhouts** [comment]
This is implemented in #181, but I did not put an option for it in the user preference window (I will eventually, I just don't feel like bothering with adding locale strings and input UI stuff right now).

In order to use it, you'll have to set the `throttleDelay` preference using the advanced configuration editor (expandable section at the bottom of the usual options page). If throttleDelay is set to an integer > 0, then the main loop will process all draft messages sequentially (it is mostly asynchronous otherwise), and whenever it sends a message it will wait that number of milliseconds until it moves on to the next message.

It will not delay between checking messages that are not ready to send. If the throttleDelay value is 0 or undefined, then the whole main loop runs as usual, mostly asynchronous with no delays imposed.

**Comment by petrosmm** [comment]
Thank you @jperryhouts
