### ISSUE TITLE
Calendar clicker pops up when it's not wanted, impossible to make it go away without clicking on it

### ISSUE THREAD

**Issue by jikamens** [Extended-Thunder/send-later#74]
On macOS:

1. Compose a message.
2. Click on the Send Later button.
3. Click on the month field so that you can type the date.
4. Note that the calendar pops up.

This is all fine so far, but now:

5. Type the year, month and day without using the calendar that popped up, and then tab out of the date field.
6. Note that the calendar stays popped up.

As far as I can tell, there's literally no way to make it go away without clicking on it.

Ugh.

When the focus leaves the date, the calendar should pop down.

**Comment by jperryhouts** [comment]
That is really annoying. Seems like a bug ("feature"?) in Gecko-- same behavior in Firefox as well-- but I don't know that there's an easy javascript override to close the calendar popup. Something like:

```javascript
document.getElementById("send-date").addEventListener("blur", evt => {
  evt.target.somehow_hide_calendar_popup();
});
```

but I'm not sure what needs to happen in order to get the calendar to close. Google was surprisingly unhelpful on this.

**Comment by jperryhouts** [comment]
I'm going to close this, since there doesn't seem to be much that can be done about it. Also, since the text input is now featured more prominently than the date/time elements I'm guessing keyboard-oriented users will just use that instead.
