### ISSUE TITLE
Doesn't work at all (in Danish version of TB)

### ISSUE THREAD

**Issue by FinnVonB** [Extended-Thunder/send-later#77]
Hi Jonathan.
I've upgraded to TB 78.4.0 (32bit) and installed the nice 'send later ver.8.0.11)' as per Your email.
But it doesn't work at all - when clicking 'send' nothing happens - I click and click on the 'send' button but nothing happens so I cannot send my email -  there's is a mix of  German and Danish translations - at least that is what I see when I go to setup the addon (mix between Danish/Dutch/German?)

Maybe I'd better wait until it's finally released ?

Just upgraded TB to 78.4.1 and now the 'send' button at least sends my email but I see nothing to the 'Send Later' add on !!

**Comment by jperryhouts** [comment]
The latest release is v 8.0.15, which you can find [here](https://github.com/Extended-Thunder/send-later/releases/tag/8.0.15-rc2). You can watch for new release on the [github release page](https://github.com/Extended-Thunder/send-later/releases).

I'm going to close this issue because it's too vague for me to help with, and because it's on an outdated version. But do come back and open a new issue if you're still experiencing problems on 8.0.15. Please be specific in your issue, and check for duplicate issues first.

**Comment by FinnVonB** [comment]
I try again -  when I press the send button i DO NOT see the send-later gui as supposed, but my mail is submitted 
 - before upgrading  from TB 78.4.0 (32 bit Danish) to TB 78.4.1(32bit in danish) it did not get submitted 
 - that goes for both send-later version 8.0.11 and 8.0.15

And what relates to the translations - sorry again - there is a mix up of translations - an issue Jonathan was made aware of in May and solved (in the old version).

Select add ons in TB
Select Send later
only 3 words are in Danish "Detaljer   Indstillinger  Tilladelser" rest is supposedly German but some looks like Dutch to me and a bit English

![sendlater](https://user-images.githubusercontent.com/74063304/98392417-431b3700-2058-11eb-8ad4-09fe1092ba3d.png)
